### ISSUE TITLE
A2-security - Leverage Mechanism Rendered Ineffective by Design Flaw

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-sentiment-v2-judging#186]
A2-security

High

# Leverage Mechanism Rendered Ineffective by Design Flaw

## Summary
The Sentiment Protocol, designed as a leveraged lending platform, but it contains a flaw in its implementation that prevents users from using borrowed assets as collateral for further borrowing to create a leverage position. This limitation contradicts the protocol's core functionality and design principles, significantly impacting its ability to provide leveraged positions and capital-efficient collateral management.
## Vulnerability Detail

The Sentiment Protocol, designed as a leveraged lending platform, As stated in the documentation:

> "The Sentiment Protocol is a leveraged lending protocol, specialized for complex portfolio positions on-chain. Sentiment provides additional flexibility and extensibility of the core protocol without compromising security. Lenders benefit from adaptive risk management and borrowers benefit from capital efficient collateral management."

However, the current implementation prevents users from using borrowed assets as collateral for further borrowing, severely limiting the protocol's intended leverage capabilities.

This limitation is enforced by two main checks in the smart contracts:

1. In the `RiskEngine` contract:
```js
  function requestLtvUpdate(uint256 poolId, address asset, uint256 ltv) external {
    if (msg.sender != pool.ownerOf(poolId)) revert RiskEngine_OnlyPoolOwner(poolId, msg.sender);
 >> if (pool.getPoolAssetFor(poolId) == asset) revert RiskEngine_CannotBorrowPoolAsset(poolId);
    if (ltv > MAX_LTV) revert RiskEngine_LtvTooHigh(ltv);

    LtvUpdate memory ltvUpdate = LtvUpdate({ ltv: ltv, validAfter: block.timestamp + TIMELOCK_DURATION });
    ltvUpdateFor[poolId][asset] = ltvUpdate;

    emit LtvUpdateRequested(poolId, asset, ltv);
}
```

   This check prevents pool owners from setting a non-zero LTV for the pool's own asset.effectively keep the` LTV` to `0` for any asset that matches the pool's asset.

1. In the `RiskModule` contract:
```js
  function _getMinReqAssetValue(
    uint256[] memory debtPools,
    uint256[] memory debtValuleForPool,
    address[] memory positionAssets,
    uint256[] memory wt,
    address position
  ) internal view returns (uint256) {
    uint256 minReqAssetValue;

    uint256 debtPoolsLength = debtPools.length;
    uint256 positionAssetsLength = positionAssets.length;
    for (uint256 i; i < debtPoolsLength; ++i) {
        for (uint256 j; j < positionAssetsLength; ++j) {
            uint256 ltv = riskEngine.ltvFor(debtPools[i], positionAssets[j]);
     >>     if (ltv == 0) revert RiskModule_UnsupportedAsset(position, debtPools[i], positionAssets[j]);
            minReqAssetValue += debtValuleForPool[i].mulDiv(wt[j], ltv, Math.Rounding.Up);
        }
    }

    if (minReqAssetValue == 0) revert RiskModule_ZeroMinReqAssets();
    return minReqAssetValue;
 }
```

This check prevents positions from using assets with zero LTV as collateral.
- since `_getMinReqAssetValue` is called by `isPositionHealthy` function after each action , if the `ltv`  for any `asset-pool` pair is `0` , the function will revert.
- thus it's impossible to use borrowed assets as collateral. This directly contradicts the intended leverage mechanism, which, as confirmed by the sponsor(since there is no context about in the readme and the docs), meant to be using the borrowed funds as collateral to borrow more and so on.

- While a potential workaround might involve looping through *borrowing, swapping borrowed funds for a collateral asset, and borrowing again*, this is not feasible due to limitations in the `Position` contract's `exec` function as swap throught `exec` function isn't allowed (and it's not the expected behavior to achieve leverage as confirmed by sponsor)

```js

    function exec(address position, bytes calldata data) internal {
      // some code .. 
   >>   if (!isKnownFunc[target][funcSelector]) revert PositionManager_UnknownFuncSelector(target, funcSelector);

        Position(payable(position)).exec(target, value, data[52:]);
        emit Exec(position, msg.sender, target, funcSelector);
    }

```

- The discrepancy between the protocol's design goals and its actual implementation not only limits functionality but also raises concerns about the overall understanding and execution of the protocol's core principles.

## Impact
1. leverage position is not possible as intended which is one of the main functionality of the protocol, for a user to achieve leverage, they would need to go through a complex process of : 
   borrowing, withdrawing , swapping , deposit , and borrowing again, which is not only inefficient but also introduces additional cost and complexities. 

## Code Snippet
- https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/RiskModule.sol#L267
- https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/RiskEngine.sol#L177
- https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/PositionManager.sol#L231
## Tool used

Manual Review

## Recommendation

- allow setting non-zero LTV values for pool assets.

**Comment by elhajin** [comment]
we disagree with the judge's decision. this is not how it should work , the current implementation of the Sentiment Protocol fails to align with its intended leverage functionality. Here’s why:

-  The protocol's documentation explicitly [states](https://docs.sentiment.xyz/concepts/core-concepts/positions#collateral-isolation):
> "Leverage in Sentiment is not achieved through 'looping' as it is money markets. Instead, borrowers can borrow up to 20x the value of their collateral in a specified loan token."

 so this is not how it should work .
 
- Protocol Design: The Sentiment Protocol is designed to allow leverage by using borrowed funds as collateral for further borrowing. this is not clearly documented any where , so the right thing was to ask the sponsor about how leverage achieved which we did : 
![Screenshot from 2024-09-17 11-11-29](https://github.com/user-attachments/assets/13d3e234-cc9b-4c1c-91b2-1a99d8a660f1)


- The existing checks in the smart contracts prevent using borrowed assets as collateral, which directly contradicts the protocol's intended functionality. This limitation breaks the core leverage functionality

- there is no way to achieve leverage in the current design which clearly an issue as the protocol [claims](https://docs.sentiment.xyz/concepts/protocol) : 
> The Sentiment Protocol is a leveraged lending protocol, specialized for complex portfolio positions on-chain...

**Comment by obou07** [comment]
Escalate , 
the above [comment](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/186#issuecomment-2355281832)

**Comment by sherlock-admin3** [comment]
> Escalate , 
> the above [comment](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/186#issuecomment-2355281832)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
@ruvaag can I have your opinion here?

**Comment by cvetanovv** [comment]
This issue can be valid because the core functionality of the protocol does not work. The sponsor's comment and the documentation confirm this. 
The inability to use borrowed assets as collateral impacts the efficiency and usability of the protocol's core leverage functionality. 

I am planning to accept the escalation and make this issue Medium.

**Comment by Nihavent** [comment]
@cvetanovv  I thought I'd add some color to this issue as the sponsor hasn't responded.


I also questioned the leverage mechanism of the system. As this issue describes, it seems impossible to take leverage because for any given LTV, the required collateral exceeds the debt amount (therefore no leverage):

<img width="900" alt="Screenshot 2024-10-06 at 21 27 04" src="https://github.com/user-attachments/assets/36fd14d3-f8a7-4986-a16b-c36d86398823">

The sponsor described the system's leverage in this way:

<img width="667" alt="Screenshot 2024-10-06 at 21 29 26" src="https://github.com/user-attachments/assets/4ff3fe2e-09cf-4776-91c5-7c3586fac36d">

Meaning if I put up 1e18 asset1 collateral, and borrow 0.5e18 asset2 (assume they have the same value), I can `exec()` 1.5e18 worth of assets in Defi to earn yield. Given 1.5e18 is more than my original 1e18 collateral, I am earning yield with leverage.


Also, please note that borrowed assets can be swapped into assets that do have an LTV set, and then re-borrowed against. Below is a test to validate this, in which a user deposits 1e18 assets, borrows against it, swaps the borrowed assets into valid collateral, and can further borrow against this position:

```javascript
    function testLeverageViaSwapping() public {
        vm.startPrank(user);
        asset2.approve(address(positionManager), 1e18);

        // deposit 1e18 asset2, borrow 1e18 asset1
        Action[] memory actions = new Action[](7);
        (position, actions[0]) = newPosition(user, bytes32(uint256(0x123456789)));
        actions[1] = deposit(address(asset2), 1e18);
        actions[2] = addToken(address(asset2));
        actions[3] = borrow(fixedRatePool, 1e18);
        actions[4] = approve(address(mockswap), address(asset1), 1e18);
        bytes memory data = abi.encodeWithSelector(SWAP_FUNC_SELECTOR, address(asset1), address(asset3), 1e18);
        actions[5] = exec(address(mockswap), 0, data);
        actions[6] = addToken(address(asset3));
        positionManager.processBatch(position, actions);
        vm.stopPrank();
        assertTrue(riskEngine.isPositionHealthy(position));

        {
        (uint256 totalAssetValue, uint256 totalDebtValue, uint256 minReqAssetValue) = riskEngine.getRiskData(position);

        assertEq(totalAssetValue, 2e18);
        assertEq(totalDebtValue, 1e18);
        assertEq(minReqAssetValue, 2e18);
        }

    }
```

I asked the sponsor if the output of this test is considered leverage and was told yes:

<img width="764" alt="Screenshot 2024-10-06 at 21 51 30" src="https://github.com/user-attachments/assets/82555a41-0a13-471d-a46f-72375e8b90f9">


<img width="748" alt="Screenshot 2024-10-06 at 22 01 04" src="https://github.com/user-attachments/assets/6d6a2f95-0905-40b7-8f93-5bc31b4d1ab6">




If you need more information as to why the borrowAsset is not able to be used as collateral consult the Guardian audit finding ("C-02 Free Borrowing When Collateral Is The Same Asset")
 




With all of the above information, I was lead to believe that leverage was working as intended.

**Comment by cvetanovv** [comment]
@Nihavent , thanks for the comment!

I don't have the sponsor's opinion on this issue, but from your comment, it is quite clear that this is an intended design. 
The Guardian audit finding(C-02) also proves that they allowed borrowed assets as collateral initially but removed it to fix a critical vulnerability.

Planning to reject the escalation and leave the issue as is.

**Comment by aliX40** [comment]
Fixing a bug doesn't mean breaking a core functionality.
@cvetanovv, sorry, but I really didn't understand why it's clear to you that this is an intended design. And to be honest, I don't know what the protocol means by "leverage" by now, because if we take @Nihavent's comment, there is no leverage (if you use your collateral and borrowed funds to earn yield, that's the case for Aave, for example, and there is no leverage here), while the docs claim that it's up to 20x leverage without looping.
About swapping borrowed funds to borrow more, it's not allowed because of the isKnownFunc check, as the sponsor confirmed, and it’s basically looping (they have an allowed swap in the test setup, which is used by @Nihavent for testing).
- Can you get up  to 10x leverage in the current system without loopping ? if yes how ? if no, is this not an issue ?

**Comment by Nihavent** [comment]
>"And to be honest, I don't know what the protocol means by "leverage" by now, because if we take @Nihavent's comment, there is no leverage (if you use your collateral and borrowed funds to earn yield, that's the case for Aave, for example, and there is no leverage here), while the docs claim that it's up to 20x leverage without looping."

Based on my [comment](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/186#issuecomment-2395741749) I do believe the sponsor considers this situation leverage in the same way that borrowing USDC against my ETH and swapping it into ETH gives me leveraged exposure to ETH.

>"About swapping borrowed funds to borrow more, it's not allowed because of the isKnownFunc check, as the sponsor confirmed, and it’s basically looping (they have an allowed swap in the test setup, which is used by @Nihavent for testing)."

It was also used in a test written by the Sentiment team `testMultiPoolProfitScenario()`.

>"Can you get up to 10x leverage in the current system without loopping ? if yes how ? if no, is this not an issue ?"

No I don't believe this is possible without swapping, and therefore I completely understand why you submitted this issue. I decided to use the information the sponsor gave me to override the docs.

**Comment by elhajin** [comment]
- @Nihavent, based on what the sponsor said in your discussion, they confirmed that the position is leveraged based on the totalAssetValue , which indeed a leverage of 2x . However, he did't confirm that this should be achieved through swapping borrowed assets (looping). In fact, during our discussion, the sponsor confirmed the opposite, stating that looping isn't possible and is not intended to achieve leverage, which is also confirmed in the documentation

-  there is no test for leverage using `mockSwap`.

To summarize, leverage is only possible through looping (I think we agree on that), and it’s up to the judge to decide whether this is the intended design or not

**Comment by ruvaag** [comment]
I don't believe this is a valid issue since pool borrows not being borrowable are by design

this is a result of C-02 in the Guardian, i'm curious if there is any issue in their finding itself

the intended effect of this restriction is not "leverage mechanism rendered ineffective" but rather "users can't just borrow and leave funds in their pool for no apparent purpose, and must use them for something". this change ensures that borrowed assets are actually put to use

**Comment by cvetanovv** [comment]
After the sponsor's comment, we can confirm that this is a design decision, and we don't have an issue here. 

My decision is to reject the escalation.

**Comment by WangSecurity** [comment]
The decision will be applied tomorrow morning.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [obou07](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/186/#issuecomment-2355570169): rejected
