### ISSUE TITLE
EgisSecurity - User can make free borrows by swapping borrowed funds for the collateral assets inside `processBatch`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-sentiment-v2-judging#303]
EgisSecurity

High

# User can make free borrows by swapping borrowed funds for the collateral assets inside `processBatch`

### Summary

There is an issue inside [PositionManager#processBatch](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/PositionManager.sol#L238-L245) function, which may result in user borrowing funds and then swapping those funds for the collateral of the loan, which will result in free borrow for him with no personal funds.

### Root Cause

[PositionManager#processBatch](https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/PositionManager.sol#L238-L245) can combine multiple actions for user position and check if the position is healthy only after the loop of actions. User can borrow all funds of all pools with no collateral, use them how he wants and after that check if his position is healthy. This is a problem, because user can borrow all the liquidity of a pool, which supports token X as collateral, swap the borrowed funds for X and then use those funds as collateral for the debt. This is big problem, because by following way user don't risk a collateral and can use a large borrow to long/short an assets. If the borrowed fund decrease in price, he can withdraw collateral, which is not owned by him. If, instead loan increases in price, he don't risk being liquidated, because the collateral itself is the loan. 

Sponsor has provided [real values](https://gist.github.com/ruvaag/58c9fc2e5c139451c83c21fda27b77a2), which will be used as approved function calls for a position and authorized addresses to be approved for position tokens.
To accomplish the exploit, user can use `Pendle` router address and it's approved functions: `swapExactTokenForPt ` and `swapExactPtForToken` to swap the loan for the collateral funds, or we can chose to swap to native eth and send to receiver, which will give execution to exploiter contract, which can perform the swap and send the collateral funds to the position. Note that if the loan has a LTV of 80-90%, user will have to provide only 10-20% of personal capital to leverage the loan.

### Internal pre-conditions

1. We assume that PositionManger has approved [sponsor provided](https://gist.github.com/ruvaag/58c9fc2e5c139451c83c21fda27b77a2) addresses and functions. 

### External pre-conditions

1. We assume there is a pendle market, which underlying asset is ETH (It is supported by sponsor's list)

### Attack Path

Imagine the following scenario:
We assume a tvl of 100% for the following pool to simplify calculations. In real example, we will assume that exploiter has provided `100% - ltv` to position.

1. We have a WETH lending pool with $100K liquidity and USDC as supported collateral with 100%
2. Exploiter creates a position with USDC asset and sends 1$ PT weETH to his position.
3. He creates a malicious contract with a fallback function, which call unsiwapv3 router to swap all his balance of WETH to USDC and send the USDC to the position contract.
4. Exploiter calls `PositionManager#processBatch`:
- on the first iteration, he borrows all $100K WETH from the lending pool.
- on the second iteration he uses `Position#transfer`to send all WETH from position to the malicious contract 
- on third iteration he uses `Position#approve` to approve Peldle router for the PT weETH tokens from the beginning 
- on fourth iteration he uses `Position#exec` to call `PendleRouter#swapExactPtForToken(address,address,uint256,tuple,tuple)` providing `TokenOutput` with the address of the malicious contract and `SwapType.ETH_WETH` and he uses 1$ PT weETH from the beginning. 
- - The following will result in [swapping the pt token](https://github.com/pendle-finance/pendle-core-v2-public/blob/11253615dc71191545b1f287c17a1c9c014ff7e9/contracts/router/ActionSwapPTV3.sol#L49-L62) and [sending the target](https://github.com/pendle-finance/pendle-core-v2-public/blob/11253615dc71191545b1f287c17a1c9c014ff7e9/contracts/router/base/ActionBase.sol#L91-L96) contract [native funds](https://github.com/pendle-finance/pendle-core-v2-public/blob/11253615dc71191545b1f287c17a1c9c014ff7e9/contracts/core/libraries/TokenHelper.sol#L23-L28), which will trigger the fallback
- - Malicious contract swap $100K WETH for $100K USDC and sends them back to the position
5. Expoiter `processBatch` exits successfully, because the position is healthy, having 100% borrow capacity 

### Impact

- Free leverage trading with large volumes without any risk
- Inflate utilization rate + interest rates 
- Reduce pool liquidity at no cost, which can result in withdraw DoS for LPs
- Increase the risk of bad debt

### Mitigation

Always ensure that the collateral is provided and then borrow the funds.

**Comment by 0xdeth** [comment]
Escalate

Hey, the following is not a standard trade, but a serious exploit which allows you to be exposed to the profit of a crypto asset worth 9.5X (for LTV of 95%) higher than your own capital, which is wrong and lead to enormous risks for Sentiment and it's depositors. This path is practically the same as [C-2 in Guardian's](https://github.com/sentimentxyz/protocol-v2/blob/master/audits/sentiment_v2_guardian.pdf) report, but we take into consideration the LTV values from the README.

Here are some points on why the following is beneficial for an exploiter, who don't risk. 
- **Margin trading without the risks/downsides.** Given the example when the collateral goes up, we execute the same attack as in Step 3 in the report but we swap the collateral for the borrow asset, we repay the loan and we retrieve the profit. Free margin trading with large volumes without the downsides. 
- **This increases utilization ratio of the pool, which increases interest rates unfairly for other borrowers.** The following may be thought of as a manipulation of the utilization ratio and a depositor in pool may use it, so other borrowers are forced to pay higher to him. He makes a borrow, which is backed by the borrow itself, so he doesn't risk own capital (or very small amount), but drastically increases the utilization rate.
- **Increases risk of bad debt.**. As the risk and losses for the exploiter are very low, he is incentivized to execute the path for high amounts and close to the liquidation limit. The following drastically increases the risk of bad debt for the protocol. 
- **Possibility of locking up high amounts of liquidity** from the pool which may DoS borrowers from using the pool under certain conditions (if there are 100k in borrow assets we execute the attack and borrow all assets, there are no assets left to be borrowed).

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Hey, the following is not a standard trade, but a serious exploit which allows you to be exposed to the profit of a crypto asset worth 9.5X (for LTV of 95%) higher than your own capital, which is wrong and lead to enormous risks for Sentiment and it's depositors. This path is practically the same as [C-2 in Guardian's](https://github.com/sentimentxyz/protocol-v2/blob/master/audits/sentiment_v2_guardian.pdf) report, but we take into consideration the LTV values from the README.
> 
> Here are some points on why the following is beneficial for an exploiter, who don't risk. 
> - **Margin trading without the risks/downsides.** Given the example when the collateral goes up, we execute the same attack as in Step 3 in the report but we swap the collateral for the borrow asset, we repay the loan and we retrieve the profit. Free margin trading with large volumes without the downsides. 
> - **This increases utilization ratio of the pool, which increases interest rates unfairly for other borrowers.** The following may be thought of as a manipulation of the utilization ratio and a depositor in pool may use it, so other borrowers are forced to pay higher to him. He makes a borrow, which is backed by the borrow itself, so he doesn't risk own capital (or very small amount), but drastically increases the utilization rate.
> - **Increases risk of bad debt.**. As the risk and losses for the exploiter are very low, he is incentivized to execute the path for high amounts and close to the liquidation limit. The following drastically increases the risk of bad debt for the protocol. 
> - **Possibility of locking up high amounts of liquidity** from the pool which may DoS borrowers from using the pool under certain conditions (if there are 100k in borrow assets we execute the attack and borrow all assets, there are no assets left to be borrowed).

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by neko-nyaa** [comment]
Guardian audit's C2 is free borrowing **if and when** the collateral asset is the same as the borrow. This issue describes a use-case of flashloaning, not an exploit. You can do this on Aave and any modern lending protocol as well: Deposit some collateral, make a huge borrow, swap it to collateral, collateralize it. This very technique is even implemented for the user in many lending protocols, e.g. Arcadia which even has a contest on Sherlock. A position with higher size than the initial capital is called a "leveraged position", and is a fundamental and basic technique in margin trading.

The submitter, as well as the report, has left out the following details which make this a non-attack:
- When the "attacker" leverages their position, the pool's interest increases. But that is exactly its job: to increase incentives for lending, and disincentivizes borrowing, when the pool's liquidity is low. Any normal borrowing in any lending protocol (and even banks in tradfi) has this effect.
- If you leverage your position up to max, you will be exposed to max price exposure, as well as max interest, which fortifies the lead judge's reasoning of position being liquidated as soon as it is created. Any max leverage position is subject to the same risk.
- Liquidity is liquidity: They are capital available for borrowing. How is "able to borrow all the allowed funds" is a bug?
- The example in the report doesn't work. If you start with $1 in capital, you borrow $100k and you collateralize that $100k, you end up with $100,001 collateral and $100,000 debt. This is not 95% LTV, it requires 99.999% LTV. For it to work with 95% LTV, you need $5000 starting collateral, which are all at risk of immediately lost upon liquidation in the next few blocks solely due to the huge interest.
- You are swapping $100,000 and expect to get $100,000 back, without any price impact or swap fees. The real value you will get is even less, which leaves even less funds for re-collateralizing.

In other words, this report describes a use-case of lending protocols, particularly a use-case of flashloaning. It doesn't describe any exploits, and has failed to show any loss of funds aside from normal risks in any lending protocol (defi or tradfi).

**Comment by cvetanovv** [comment]
The scenario described aligns more closely with a legitimate margin trading use case rather than an exploit. 

The protocol's mechanisms—such as interest rate adjustments, liquidation risks, and potential swap fees—serve as natural deterrents, making it difficult for the attacker to profit without significant risk. 

Additionally, leveraging a position is a common practice in lending protocols, and the risks outlined are part of the intended behavior of such systems. So, we don't have an exploit or unfair advantage here.

Planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [EgisSecurity](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/303/#issuecomment-2355049085): rejected
