### ISSUE TITLE
ZeroTrust - In liquidateBadDebt, transferring all the assets from the position to the protocol’s owner is unfair to the lender, as it increases the lender’s losses.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#307]
ZeroTrust

High

# In liquidateBadDebt, transferring all the assets from the position to the protocol’s owner is unfair to the lender, as it increases the lender’s losses.

## Summary
In liquidateBadDebt, all the assets from the position are transferred to the protocol’s owner, while the lender bears the full loss of the entire borrowed amount, not just the under-collateralized portion (i.e., debtValue - assetValue). This results in an unfair outcome for the lender.

## Vulnerability Detail
```javascript
function liquidateBadDebt(address position) external onlyOwner {
        riskEngine.validateBadDebt(position);

        // transfer any remaining position assets to the PositionManager owner
        address[] memory positionAssets = Position(payable(position)).getPositionAssets();
        uint256 positionAssetsLength = positionAssets.length;
        for (uint256 i; i < positionAssetsLength; ++i) {
            uint256 amt = IERC20(positionAssets[i]).balanceOf(position);
@>>            try Position(payable(position)).transfer(owner(), positionAssets[i], amt) { } catch { }
        }

        // clear all debt associated with the given position
        uint256[] memory debtPools = Position(payable(position)).getDebtPools();
        uint256 debtPoolsLength = debtPools.length;
        for (uint256 i; i < debtPoolsLength; ++i) {
@>>            pool.rebalanceBadDebt(debtPools[i], position);
@>>            Position(payable(position)).repay(debtPools[i], type(uint256).max);
        }
    }
```
We can see in the liquidateBadDebt function that all of the position’s assets are transferred to the owner, but none of the debt is actually repaid.
```javascript
  function rebalanceBadDebt(uint256 poolId, address position) external {
        PoolData storage pool = poolDataFor[poolId];
        accrue(pool, poolId);

        // revert if the caller is not the position manager
        if (msg.sender != positionManager) revert Pool_OnlyPositionManager(poolId, msg.sender);

        // compute pool and position debt in shares and assets
        uint256 totalBorrowShares = pool.totalBorrowShares;
        uint256 totalBorrowAssets = pool.totalBorrowAssets;
        uint256 borrowShares = borrowSharesOf[poolId][position];
        // [ROUND] round up against lenders
        uint256 borrowAssets = _convertToAssets(borrowShares, totalBorrowAssets, totalBorrowShares, Math.Rounding.Up);

        // rebalance bad debt across lenders
@>>        pool.totalBorrowShares = totalBorrowShares - borrowShares;
        // handle borrowAssets being rounded up to be greater than totalBorrowAssets
@>>        pool.totalBorrowAssets = (totalBorrowAssets > borrowAssets) ? totalBorrowAssets - borrowAssets : 0;
        uint256 totalDepositAssets = pool.totalDepositAssets;
@>>        pool.totalDepositAssets = (totalDepositAssets > borrowAssets) ? totalDepositAssets - borrowAssets : 0;
        borrowSharesOf[poolId][position] = 0;
    }
```
In the rebalanceBadDebt function, the debt is only cleared at the accounting level, without transferring the actual funds needed to repay the debt. Directly reducing borrowAssets from totalDepositAssets forces all lenders to bear the loss of the borrowed funds.

```javascript
 function repay(uint256 poolId, uint256) external onlyPositionManager {
        if (POOL.getBorrowsOf(poolId, address(this)) == 0) debtPools.remove(poolId);
    }
```
We can see that in the position.repay() function, there is also no actual transfer of funds to repay the debt.
## Impact
The lender bears the full loss of the borrowed funds, not just the under-collateralized portion (i.e., debtValue - assetValue), while the owner profits. This is extremely unfair to the lender.
## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/PositionManager.sol#L446

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/Pool.sol#L528
## Tool used

Manual Review

## Recommendation
The protocol should either repay all of the debt or sell the position’s collateral (assets) into the debt token to cover the outstanding debt.

**Comment by 0xdeth** [comment]
Escalate

Isn't this a design choice? We've never seen bad debt handled in any other way, also sending the assets to the owner seems the logical thing to do, as the function does have the `onlyOwner` modifier. The owner can then send the collateral to the lenders after the liquidation which seems like a reasonable thing to do.

The issue itself is marked as `Sponsor Disputed` so it's likely a design choice.

We just want the judge to take a second look at this.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Isn't this a design choice? We've never seen bad debt handled in any other way, also sending the assets to the owner seems the logical thing to do, as the function does have the `onlyOwner` modifier. The owner can then send the collateral to the lenders after the liquidation which seems like a reasonable thing to do.
> 
> The issue itself is marked as `Sponsor Disputed` so it's likely a design choice.
> 
> We just want the judge to take a second look at this.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Honour-d-dev** [comment]
It's not just about sending the assets to the owner.

The **issue** is there's no available logic for distributing the seized assets back to the lenders (_you can highlight it if there is_). The protocol also doesn't mention any off-chain logic/process to achieve this, and if we're being honest such logic should be on-chain so user's know what they're dealing with.

**Comment by Nihavent** [comment]
Given https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/66 is a known issue, this issue must also be known. 
The protocol team must be aware that depositors sustain losses upon rebalancing bad debt debt for them to understand why users would fronrun liquidateBadDebt().

This is clearly working exactly as designed. Any suggestions to make this more fair or transparent are design recommendations.

**Comment by Honour-d-dev** [comment]
> Given https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/66 is a known issue, this issue must also be known. 
> The protocol team must be aware that depositors sustain losses upon rebalancing bad debt debt for them to understand why users would fronrun liquidateBadDebt().
> 
> This is clearly working exactly as designed. Any suggestions to make this more fair or transparent are design recommendations.

except there is no **rebalancing bad debt** in the protocol code. or is there?

The functionality is completely missing

**Comment by Nihavent** [comment]
> > Given #66 is a known issue, this issue must also be known.
> > The protocol team must be aware that depositors sustain losses upon rebalancing bad debt debt for them to understand why users would fronrun liquidateBadDebt().
> > This is clearly working exactly as designed. Any suggestions to make this more fair or transparent are design recommendations.
> 
> except there is no **rebalancing bad debt** in the protocol code. or is there?
> 
> The functionality is completely missing


After transfering the assets to the protocol multisig, the function `rebalanceBadDebt()` removes the debt from the pool's state. So I agree it does not 'rebalance' the debt at all, so the functionality is missing.

What I'm saying is this fact was clearly known and intended by the sponsor. If it were not known they could not have left this comment in the [readme](https://audits.sherlock.xyz/contests/349?filter=questions):

>"The purpose of bad debt liquidation is to ensure that the pool can revert back to a functional state after socialization of bad debt. It is expected that a small share of lenders might be able to withdraw funds before the function is executed." 

So it is working as expected, even if we don't agree with the design

**Comment by Honour-d-dev** [comment]
@Nihavent but there's no **socialisation of bad debt** as the README claims.

Or does socialisation of bad debt mean sending the assets to the owner?

**Comment by Nihavent** [comment]
In my view the socialisation of bad debt is the reduction in depositor share value equal to the value of bad debt liquidated, ie. the burden of the debt was shared (socialised) among the lenders. 

Could this be better? Yes! But that’s a design recommendation

**Comment by Honour-d-dev** [comment]
> In my view the socialisation of bad debt is the reduction in depositor share value equal to the value of bad debt liquidated, ie. the burden of the debt was shared (socialised) among the lenders. 
> 
> Could this be better? Yes! But that’s a design recommendation 

I Believe we're saying the same thing. the README talks about socialising bad debt.

But it's not implemented in the code (I.e. the burden of the debt is not shared among the lenders)

**Comment by Nihavent** [comment]
> > In my view the socialisation of bad debt is the reduction in depositor share value equal to the value of bad debt liquidated, ie. the burden of the debt was shared (socialised) among the lenders.
> > Could this be better? Yes! But that’s a design recommendation
> 
> I Believe we're saying the same thing. the README talks about socialising bad debt.
> 
> But it's not implemented in the code (I.e. the burden of the debt is not shared among the lenders)

It is implemented in `rebalanceBadDebt ()`:

```javascript
pool.totalDepositAssets = (totalDepositAssets > borrowAssets) ? totalDepositAssets - borrowAssets : 0;
        borrowSharesOf[poolId][position] = 0;
```

The pool's assets are reduced by the bad debt amount, so every depositShare is devalued equally.

What's not implemented is the sale of the available collateral and allocation back to the lenders to minimize their losses. 

Anyway, best to leave this for the judge I just wanted to express my view in light of https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/66 being a known issue.

**Comment by Tomiwasa0** [comment]
Well done everyone, @Nihavent . Because front running is known, doesn't mean the right thing was done during the socialization process. 
The code allows less liquidity to be present sometimes by checking address this balance, no problem,  but when it comes to reducing the losses during rebalancing the accounting done is incorrect.

> /// @notice Fetch amount of liquid assets currently held in a given pool
    function getLiquidityOf(uint256 poolId) public view returns (uint256) {
        PoolData storage pool = poolDataFor[poolId];
        uint256 assetsInPool = pool.totalDepositAssets - pool.totalBorrowAssets;
        uint256 totalBalance = IERC20(pool.asset).balanceof(address(this));
        return (totalBalance > assetsInPool) ? assetsInPool : totalBalance;
    }

 So in a case when we have 1 million dollars. A whale takes 800 thousand with a TVL of 95%. Meaning if the 800 thousand becomes bad debt, the total deposit is reduced to 200,000 even though the loss was just about 200-250k.

For more info I advise you to read their Documentation, which states that we are to  Socialize LOSSES. 

Admin is trusted to swap and send the remaining liquidity back to the pool. 

But quote me anywhere - there is no way, absolutely no way for the user to claim these funds since we cannot increase total deposited assets without depositing and creating more shares. If there is kindly let us know, thanks.

**Comment by cvetanovv** [comment]
I disagree with the escalation.

While the Protocol may have intended this design, it creates an imbalance in which creditors can unfairly bear the burden of bad debts. This leads to a loss of funds for the users, which I think deserves Medium severity.

Planning to reject the escalation and leave the issue as is.

**Comment by Nihavent** [comment]
> While the Protocol may have intended this design, it creates an imbalance in which creditors can unfairly bear the burden of bad debts. This leads to a loss of funds for the users, which I think deserves Medium severity.

1. We agree this in the intended design by the protocol.
2. We all must also agree that admin wallet who receives the collateral is trusted. 
So, what imbalance are you referring to? We must trust the admin is infallible and will correctly allocate the sold collateral back to depositors. 

According to [this](https://github.com/sherlock-protocol/sherlock-v2-docs/blob/e7dc89270b05f8d2fcee69dc4204c7a2b8fb4cf9/audits/judging/judging/README.md?plain=1#L101) rule, the report must demonstrate there is a material loss of funds to validate a design improvement:

> 8. **User experience and design improvement issues:**  Issues that cause minor inconvenience to users where there is no material loss of funds are not considered valid. Funds are temporarily stuck and can be recovered by the administrator or owner. Also, if a submission is a design opinion/suggestion without any clear indications of loss of funds is not a valid issue.

The admin/owner <u>does</u> receive the funds and can send them back to the depositors. For there to be a material loss of funds it would require the admin to not correctly allocate the claimed collateral which contradicts the admin being trusted and infallible.

As shown in the rule, this is just a minor inconvenience to the users as they have to wait for the admin to calculate and allocate some funds back to them. I had this rule in mind when participating in the judging contest and I haven't seen any new information brought up that would indicate this rule doesn't apply.

**Comment by Tomiwasa0** [comment]
Much respect to you sir @Nihavent, Admin will indeed return the money back to the contract has already explained by everyone. Noted the main issue is in reducing total deposit not admin's action. We reduce the total deposit in the VAULT, no problem but Note this is a Vault, there is no way I repeat and you can quote me anywhere. No way for the admin to return these funds to Increment the total deposit again for users to claim. 

There is a limitation here
> uint256 assetsInPool = pool.totalDepositAssets - pool.totalBorrowAssets;
uint256 totalBalance = IERC20(pool.asset).balanceof(address(this));
return (totalBalance > assetsInPool) ? assetsInPool : totalBalance;

The best option is for proper accounting to be done to the Vault asset and funds be transferred later.
Even if the money is sent to the contract we will return a claimable amount lesser than the address this balance. Read #211 also for more clarity.

**Comment by Nihavent** [comment]
I agree there is no way for the admin to deposit these funds into the pool for the users, but this doesn't mean there is no way to send them the funds. We don't know how they intend to do this but as long as the admin is trusted we assume they will do this in a fair way (yes, ideally this would be on-chain for transparency but that is a design recommendation). 

As far as I can see there is no accounting issue at all in this process. After the 'rebalancing' of bad debt, the depositShares will be worth less than they were before by the amount of bad debt sustained by the pool which works as intended. Check out the following scenario:

1. asset1 is priced at 1e18, asset2 is priced at 1e18
2. Alice and Bob deposit 1e18 asset1 into fresh pool
3. Carol deposits 1.5e18 asset2 into the same pool and borrows 1e18 asset1, the position is healthy
4. The price of asset2 halves and is now worth 0.5e18, the position now has 0.75e18 worth of collateral and 1e18 worth of debt <u>(0.25e18 worth of bad debt)</u>
5. The bad debt is liquidated and 1e18 worth of asset1 is erased from the pool without changing the amount of depositShares
6. As part of `liquidateBadDebt` The 1.5e18 asset2 (worth 0.75e18 asset1) is sent to the admin 
7. Admin took a snapshot when bad debt was liquidated and saw that 50% of this remaining collateral belongs to Alice, and 50% belongs to Bob.
8. Admin sells the seized collateral for asset1, and sends 0.375e18 to Alice and 0.375e18 to Bob.
9. Alice and Bob now each have 0.5e18 worth of asset1 in the pool, and 0.375e18 worth of asset1 in their EOAs.
10. The value of losses here exactly match the value of bad debt that the pool sustained (excluding slippage and gas fees):
    - Alice and Bob have each lost 0.125e18 (1e18 - 0.875e18). Their combined losses are 0.25e18.
    - <u>Note that 0.25e18 is the exact value of bad debt that Carol had in step 4</u> 
11. If Alice and Bob wish to deposit the returned liquidity into the pool they're free to do so. They will of course get more shares for each new unit deposited as the value of each share has declined, however their total shares are worth the correct amount of liquidity.

The only losses that have occurred were due to the bad debt worth 0.25e18. There is no imbalance or accounting issue.

**Comment by Nihavent** [comment]
I agree there is no way for the admin to deposit these funds into the pool for the users, but this doesn't mean there is no way to send them the funds. We don't know how they intend to do this but as long as the admin is trusted we assume they will do this in a fair way (yes, ideally this would be on-chain for transparency but that is a design recommendation). 

As far as I can see there is no accounting issue at all in this process. After the 'rebalancing' of bad debt, the depositShares will be worth less than they were before by the amount of bad debt sustained by the pool which works as intended. Check out the following scenario:

1. asset1 is priced at 1e18, asset2 is priced at 1e18
2. Alice and Bob deposit 1e18 asset1 into fresh pool
3. Carol deposits 1.5e18 asset2 into the same pool and borrows 1e18 asset1, the position is healthy
4. The price of asset2 halves and is now worth 0.5e18, the position now has 0.75e18 worth of collateral and 1e18 worth of debt <u>(0.25e18 worth of bad debt)</u>
5. The bad debt is liquidated and 1e18 worth of asset1 is erased from the pool without changing the amount of depositShares
6. As part of `liquidateBadDebt` The 1.5e18 asset2 (worth 0.75e18 asset1) is sent to the admin 
7. Admin took a snapshot when bad debt was liquidated and saw that 50% of this remaining collateral belongs to Alice, and 50% belongs to Bob.
8. Admin sells the seized collateral for asset1, and sends 0.375e18 to Alice and 0.375e18 to Bob.
9. Alice and Bob now each have 0.5e18 worth of asset1 in the pool, and 0.375e18 worth of asset1 in their EOAs.
10. The value of losses here exactly match the value of bad debt that the pool sustained (excluding slippage and gas fees):
    - Alice and Bob have each lost 0.125e18 (1e18 - 0.875e18). Their combined losses are 0.25e18.
    - <u>Note that 0.25e18 is the exact value of bad debt that Carol had in step 4</u> 
11. If Alice and Bob wish to deposit the returned liquidity into the pool they're free to do so. They will of course get more shares for each new unit deposited as the value of each share has declined, however their total shares are worth the correct amount of liquidity.

The only losses that have occurred were due to the bad debt worth 0.25e18. There is no imbalance or accounting issue.

As for the limitation you mentioned,  
- If both Alice and Bob chose to redeposit the 0.375e18 asset1 from step 11`Pool::getLiquidityOf()` will return 1.75e18 (1e18 + 2 * 0.375e18) which is correct
- If neither Alice, nor Bob chose to redeposit the 0.375e18 asset1 from step 11, it will return 1e18 which is also correct.

**Comment by Tomiwasa0** [comment]
I believe if we have over 20,000 plus or more users this system from 7-11 is inefficient. 
Also, The above steps was never mentioned in all the Documentations. 
IF there are any offchain design choice THE README/ DOCs should have clearly stated this. 
The above is lovely but This is just a possible assumption of how it could work. Which could be more inefficient as the pool grows.

**Comment by Tomiwasa0** [comment]
Why does admin need to deposit personally into the users account. 
I invested to get interest but each time there is a bad debt my funds are withdrawn and I have to re deposit into the Vault again. It's totally inefficient. 
The best solution here is in the report.

**Comment by Nihavent** [comment]
Of course the example I gave is inefficient. I gave the example to show an admin receiving the funds could allocate them, and there is no accounting issue/imabalance/limitation in the pool. Therefore there is no material loss of funds and this is a [design recommendation](https://github.com/sherlock-protocol/sherlock-v2-docs/blob/e7dc89270b05f8d2fcee69dc4204c7a2b8fb4cf9/audits/judging/judging/README.md?plain=1#L101):

> 8. User experience and design improvement issues: Issues that cause minor inconvenience to users where there is no material loss of funds are not considered valid. Funds are temporarily stuck and can be recovered by the administrator or owner. Also, if a submission is a design opinion/suggestion without any clear indications of loss of funds is not a valid issue.

There is absolutely no reason why we should trust the admin to do everything correctly except reallocating user deposits which were seized as part of a bad debt liquidation.

**Comment by Tomiwasa0** [comment]
IF there are any offchain design choice THE README/ DOCs should have clearly stated this. If you can point this out no problem.

**Comment by Tomiwasa0** [comment]
"The purpose of bad debt liquidation is to ensure that the pool can revert back to a functional state after socialization of bad debt. It is expected that a small share of lenders might be able to withdraw funds before the function is executed." 
- a small shares won't be able to withdraw funds after socialization they should be able to withdraw from the vault and not others wise. Again are there an mechanism to prevent shares withdrawals before debt socialization?

**Comment by Nihavent** [comment]
> IF there are any offchain design choice THE README/ DOCs should have clearly stated this. If you can point this out no problem.

We don’t need to know how the admin intends to proceed when they receive the funds. All we need to know is:
- Admin is trusted
- Admin does receive all of the available collateral, and could distribute them back to users fairly (see point 1)
- The judge has agreed this was a design decision and it’s working as designed
- There is no imbalance if we trust the admin (as the judge claimed) 
- There is no limitation in getLiquidityOf() after bad debt is rebalanced (as @Tomiwasa0 claimed)


> "The purpose of bad debt liquidation is to ensure that the pool can revert back to a functional state after socialization of bad debt. It is expected that a small share of lenders might be able to withdraw funds before the function is executed."

> a small shares won't be able to withdraw funds after socialization they should be able to withdraw from the vault and not others wise. Again are there a mechanism to prevent shares withdrawals before debt socialization?

This is getting a bit off topic now, the comment from the sponsor seems to be related to depositors front running the liquidateBadDebt call to avoid losing funds by having an active deposit when bad debt is liquidated. 

It was nice discussing this with you and I appreciate your view that this whole process should be improved. But I don’t feel like it’s a valid issue according to Sherlock rules.

**Comment by Tomiwasa0** [comment]
Same. i believe it should call for an improvement.
 Arguing won't solve anything, it never does. Let's leave the final decision to him. Thanks, it's been nice, mature and kind of official.

**Comment by 10xhash** [comment]
> I disagree with the escalation.
> 
> While the Protocol may have intended this design, it creates an imbalance in which creditors can unfairly bear the burden of bad debts. This leads to a loss of funds for the users, which I think deserves Medium severity.
> 
> Planning to reject the escalation and leave the issue as is.

If it is their intended design, loss of funds following an admin action is not considered a valid issue. Here `liquidateBadDebt` is an admin action
> An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue

**Comment by Tomiwasa0** [comment]
No one is questioning admins action. README is above the rule and in the README. 
Admin said "The purpose of bad debt liquidation is to ensure that the pool can revert back to a functional state after socialization of bad debt. It is expected that a small share of lenders might be able to withdraw funds before the function is executed.". 
a small share of lenders might be able to withdraw funds - (the impact of this finding says this is wrong), but the function does not prevent this because of the calculation done there is a POC AT #211 Kindly run it as all shares are burnt, there is no need for back and forths.

**Comment by cvetanovv** [comment]
After reviewing the discussion and the issue again, I think this is a design decision. The current liquidation mechanism transfers the remaining assets to the protocol owner after liquidating bad debt. While this process may seem inefficient and lacks transparency in how lenders are compensated, it aligns with the protocol’s intended design.

Furthermore, @10xhash is correct in his observation that even if this design or admin action results in a loss of funds, it would be invalid based on Sherlock's rules:

>Admin Input/call validation:
> - An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.

Planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [EgisSecurity](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/307/#issuecomment-2355117605): accepted
