### ISSUE TITLE
MohammedRizwan - `Pool.sol` functions are not strictly in compliance with ERC6909

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-08-sentiment-v2-judging#396]
MohammedRizwan

Medium

# `Pool.sol` functions are not strictly in compliance with ERC6909

## Summary
`Pool.sol` functions are not strictly in compliance with ERC6909

## Vulnerability Detail
As per the contest readme, `Pool.sol is strictly ERC6909 compliant`. `Pool.sol` has inherited base contract `ERC6909`.

```solidity
contract Pool is OwnableUpgradeable, ERC6909 {
```

ERC6909 has public functions which can be used by `Pool.sol` as its being inherited. The following implemented functions are not in strict compliance with ER6909.

```solidity
    function transfer(address receiver, uint256 id, uint256 amount) public virtual returns (bool) {
        balanceOf[msg.sender][id] -= amount;

        balanceOf[receiver][id] += amount;

        emit Transfer(msg.sender, msg.sender, receiver, id, amount);

        return true;
    }

    function transferFrom(address sender, address receiver, uint256 id, uint256 amount) public virtual returns (bool) {
        if (msg.sender != sender && !isOperator[sender][msg.sender]) {
            uint256 allowed = allowance[sender][msg.sender][id];
            if (allowed != type(uint256).max) allowance[sender][msg.sender][id] = allowed - amount;
        }

        balanceOf[sender][id] -= amount;

        balanceOf[receiver][id] += amount;

        emit Transfer(msg.sender, sender, receiver, id, amount);

        return true;
    }
```

As per [ERC6909 specification for `transfer()` and transferFrom()` functions](https://eips.ethereum.org/EIPS/eip-6909),

 transfer
>>MUST revert when the caller’s balance for the token id is insufficient.

 transferFrom
>> MUST revert when the caller is neither the sender nor an operator for the sender and the caller’s allowance for the token id for the sender is insufficient.
>> MUST revert when the sender’s balance for the token id is insufficient.

This `MUST` requirement of ERC6909 pertaining to both `transfer()` and `transferFrom()` functions is not complied therefore, the functions wont be able to revert in case senders balance for the token is not enough and callers allowance for sender is not sufficient.

## Impact
Failure to comply with the ERC6909 specification for methods like transfer and transferFrom which is a considered as strict compliance by protocol

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/lib/ERC6909.sol#L32-L55

## Tool used
Manual Review

## Recommendation
Ensure `Pool.sol` is in strict compliance with ERC6909.

Consider below changes:
```diff
+    /// @dev Thrown when owner balance for id is insufficient.
+    /// @param owner The address of the owner.
+    /// @param id The id of the token.
+    error InsufficientBalance(address owner, uint256 id);

+    /// @dev Thrown when spender allowance for id is insufficient.
+    /// @param spender The address of the spender.
+    /// @param id The id of the token.
+    error InsufficientPermission(address spender, uint256 id);
    
    . . . some code . . . 
    
    

    function transfer(address receiver, uint256 id, uint256 amount) public virtual returns (bool) {
+         if (balanceOf[msg.sender][id] < amount) 
+             revert InsufficientBalance(msg.sender, id);
        balanceOf[msg.sender][id] -= amount;

        balanceOf[receiver][id] += amount;

        emit Transfer(msg.sender, msg.sender, receiver, id, amount);

        return true;
    }

    function transferFrom(address sender, address receiver, uint256 id, uint256 amount) public virtual returns (bool) {
        if (msg.sender != sender && !isOperator[sender][msg.sender]) {
            uint256 allowed = allowance[sender][msg.sender][id];
+             if (allowed < amount) 
+                revert InsufficientPermission(msg.sender, id);
            if (allowed != type(uint256).max) allowance[sender][msg.sender][id] = allowed - amount;
        }
+         if (balanceOf[sender][id] < amount) 
+             revert InsufficientBalance(sender, id);
        balanceOf[sender][id] -= amount;

        balanceOf[receiver][id] += amount;

        emit Transfer(msg.sender, sender, receiver, id, amount);

        return true;
    }
```

Duplicate of #342

**Comment by 0xMR0** [comment]
Escalate

As per contest readme:

> Is the codebase expected to comply with any EIPs? Can there be/are there any deviations from the specification?
Pool.sol is strictly ERC6909 compliant

`Pool` contract is STRICTLY compliant to ERC6909 and the specification for transfer/transferFrom is a `MUST requirement` from ERC6909. 

Its explicitly needs to be reverted as per EIP.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> As per contest readme:
> 
> > Is the codebase expected to comply with any EIPs? Can there be/are there any deviations from the specification?
> Pool.sol is strictly ERC6909 compliant
> 
> `Pool` contract is STRICTLY compliant to ERC6909 and the specification for transfer/transferFrom is a `MUST requirement` from ERC6909. 
> 
> Its explicitly needs to be reverted as per EIP.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree with the Lead Judge's comment. There is also no impact to be a valid issue.

Planning to reject the escalation and leave the issue as is.

**Comment by 0xRizwan** [comment]
Hello @cvetanovv 

I believe, the following sherlock rule is applicable here as the contest readme specifically states `Pool.sol is strictly ERC6909 compliant`

> The protocol team can use the README (and only the README) to define language that indicates the codebase's restrictions and/or expected functionality. Issues that break these statements, irrespective of whether the impact is low/unknown, will be assigned Medium severity

Further, the issue highlights a `MUST` specification requirement for transfer/transferFrom which can not be ignored. Impact of issue as part of sentiment contest would be `Failure to comply with the ERC6909 specification for methods like transfer and transferFrom which is a considered as strict compliance by protocol` and it is not met which is intended by protocol.

The above sherlock rule states to assign such issues Medium severity irrespective of impact as Pool.sol MUST be ERC6909 compliant according to protocol.

**Comment by cvetanovv** [comment]
@0xRizwan the protocol strictly follows ERC6909. 

In both transfer functions, if the funds are insufficient, the transaction will revert. 

You can see, for example, in `transfer()` - https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/lib/ERC6909.sol#L33

```solidity
balanceOf[msg.sender][id] -= amount;
```

If the balance is less, the transaction will revert due to underflow. The same applies to the other function. 
This issue would be valid if your contract was a Solidity version below 0.8.0. Now it is invalid.

My decision to reject the escalation remains.

**Comment by 0xRizwan** [comment]
@cvetanovv 

Solidity v0.8.0 is released on [Dec 16, 2020](https://github.com/ethereum/solidity/releases/tag/v0.8.0) and EIP6909 is created on [April 19, 2023](https://eips.ethereum.org/EIPS/eip-6909) so it has nothing to do with underflow revert as The ERC6909 transfer/transferFrom() states to explicitely revert. For example, error like `InsufficientBalance()`. 

transfer/transferFrom() specification needs to comply this in its function.

> MUST revert when the sender’s balance for the token id is insufficient.

A reference ERC6909 implementation can be checked [here](https://eips.ethereum.org/EIPS/eip-6909).

Since, its known with v0.8.0 it would revert due to underflow and this is also known by EIP creators but still the above specification is said to be enforced. 

In general, i agree with your point but its ERC6909 requirement which is MUST so it can not be ignored. If Pool.sol was optionally ERC6909 compliant, it would have been okay but its a `STRICTLY` compliant to ERC6909.

**Comment by cvetanovv** [comment]
@0xRizwan you're not a beginner, and I don't need to explain elementary things. 

The contract that follows this standard may be below version 0.8.0. 

The other variant is that the version is above 0.8.0, but the transfer function is in the `unchecked` block.

Currently, the protocol strictly follows this standard because the transfer functions revert exactly as they should by the ERC6909 standard. 

In short:
ERC6909 standard:
> MUST revert when the sender’s balance for the token id is insufficient.

Is this followed by the protocol? 
- Yes. It is followed. 

Does the function revert if there is not enough balance?
- Yes, the transfer function revert.

Escalation will be rejected.

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #342

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xMR0](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/396/#issuecomment-2351940181): rejected
