### ISSUE TITLE
bhilare_ - SuperPool::removePool() function will ALWAYS revert if `forceRemove = true` & anyone borrows from the given Base pool OR totalBorrowAssets > 0.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#455]
bhilare_

Medium

# SuperPool::removePool() function will ALWAYS revert if `forceRemove = true` & anyone borrows from the given Base pool OR totalBorrowAssets > 0.

## Summary
`SuperPool::removePool()` function which is used for removing a Base pool from Super pool, if forceRemove expected, will always revert if anyone borrows from the base pool, i.e if `pool.totalBorrowAssets > 0`, SINCE, while removing, it is expected to withdraw all assets being deposited by SuperPool in the given BasePool, which won't be able to happen, since some assets would be borrowed and hence max withdrawable amount of assets will be less than all assets amount deposited, hence WILL always revert, which breaks the functionality and would not make it possible to remove a Base Pool (if present)from SuperPool , until unless all users repay the debt amounts, which would not be in hands of protocol's.

## Vulnerability Detail
In `removePool` function  :

```javascript
function removePool(uint256 poolId, bool forceRemove) external onlyOwner {
        if (poolCapFor[poolId] == 0) return; // no op if pool is not in queue
        uint256 assetsInPool = POOL.getAssetsOf(poolId, address(this));
        if (forceRemove && assetsInPool > 0) POOL.withdraw(poolId, assetsInPool, address(this), address(this));
        _removePool(poolId);
        poolCapFor[poolId] = 0;
        emit PoolCapSet(poolId, 0);
    }
```

If `forceRemove` is being set to `True`, then the withdraw function is being called in the (Base) Pool contract.

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/Pool.sol#L339-L372

The `assetsInPool` parameter is being passed, which is returned value calculated using `POOL.getAssetsOf`, in which the `balanceOf[address(superPool)][id]` ( i.e the amount of shares SuperPool contract has, which were being minted while supplying to the base pools and depositing assets in them using `_supplyPools` internal function call made in `_deposit` function)  is being used.

So lets say using `SuperPool.deposit()` , 100 units of assets are being deposited, and for simplicity there is a single pool added.
Hence 100 shares will be minted to the SuperPool contract in the POOL.deposit() function call.

So the  `POOL.getAssetsOf`, function will return value 100 units.

Now , further moving in `SuperPool::removePool` function, it will call `POOL.withdraw` function with the assetInPool value equal to 100 units.

Now the issue is :

In the `Pool.withdraw function`, `maxWithdrawAssets` is being calculated.

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/Pool.sol#L359C4-L362C118

If anyone borrows from this Pool, then pool.totalBorrowAssets will be greater than 0.
And here the totalBalance (assets in Pool) will be equal to 100 units, as they were being supplied by the SuperPool itself.

Hence  `maxWithdrawAssets` will be less than 100.

lets say someone borrows 10 units of assets, then `maxWithdrawAssets` = 90.

Which is less than the `POOL.getAssetsOf` value of SuperPool, which was being passed as parameter while calling `POOL.withdraw`.
i.e `assets = 100`, & `maxWithdrawAssets = 90`.

And hence because of the below check : 

```javascript
if (maxWithdrawAssets < assets) revert Pool_InsufficientWithdrawLiquidity(poolId, maxWithdrawAssets, assets);
```

This function call will always revert.
This is because while removing it is being expected to withdraw all assets. But if anyone would have borrowed it, then all the assets would not be able to be withdrawn, and hence the `removePool` function call will always revert.

## Impact
`SuperPool::removePool()` function call will always revert if anyone borrow if 1 unit of asset.

Because of which if SuperPool owner would have to remove the given pool due to any reason, he won't be able to remove it , until unless all borrow amounts are being repayed, which would be based on users only, and can't be in hands of protocol.

## POC (Proof Of Concept)

For describing the same scenario above, below gist file contains the proof of code.
It required both use of SuperPool.t.sol & PositionManager.t.sol functionalities, hence made a different test contract.
Directly add this in `test/core folder`

GIST FILE : https://gist.github.com/Pranay-Bhilare/b6aba8e01ef9e7e0045a3941ffc88579

And run using command 

`forge test --mt testRemovePoolReverts -vvvv ` 

This will give the following console output : 

`Ran 1 test for test/core/test.t.sol:POCTest
[PASS] testRemovePoolReverts() (gas: 1020620)
Traces:`

And in the Traces at the end you can see : 

` [Revert] Pool_InsufficientWithdrawLiquidity(76185170914664034982717614324376362661771448584651785366001810948719059386837 [7.618e76], 90000000000000000000 [9e19], 100000000000000000000 [1e20])
    │   │   └─ ← [Revert] Pool_InsufficientWithdrawLiquidity(76185170914664034982717614324376362661771448584651785366001810948719059386837 [7.618e76], 90000000000000000000 [9e19], 100000000000000000000 [1e20])
    │   └─ ← [Revert] Pool_InsufficientWithdrawLiquidity(76185170914664034982717614324376362661771448584651785366001810948719059386837 [7.618e76], 
90000000000000000000 [9e19], 100000000000000000000 [1e20])`

It reverted with the exact reason described above.

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/SuperPool.sol#L326C1-L333C6
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/Pool.sol#L333C4-L373C1

## Tool used

Manual Review

## Recommendation

The Pool data should be fetched first, and if there are any borrowed assets, that value should be subtracted first from the `assetInPool` value, which will THEN be equal to the `maxWithdrawAssets` and then it should be passed as parameter while calling POOL.withdraw() function.

This will prevent reverting, and maximum assets will be retrieved back SAFELY.

**Comment by Pranay-Bhilare** [comment]
Escalate

@z3s I didn't understand your response for invalidating this.

This has nothing to do with the number of depositors , whether there be only 1 or other.

This functionality of setting `forceRemove` as TRUE while calling `SuperPool::removePool` is itself might be added so that ` if in future any situation arises where the SuperPool owner has to remove a particular POOL`.

Then he can do, without causing any loss to the depositors , hence forcefully withdrawing all assets back to SuperPool from the given Base Pool

But considering current implementation, the functionality cannot be used, and a pool will never be able to removed with forceApprove = True, if there is even a single unit of assets that hasn't been repayed, since it will always REVERT as explained in REPORT.

Then the only option left would be removing pool with setting `forceRemove` as FALSE, which will not retreive the Assets in the Pool, and would just remove it , causing loss for SuperPool depositors.

`One mistake while writing in report from my side, that I have written if anyone borrows even a single unit of asset, then this issue can occur`, but a user can't borrow single unit of asset since there is a `minBorrow` check while borrowing.

But if this is the argument is centered around `minBorrow` check being already present, and user/attacker would has to lose funds from his side in order to perform this DOS , then :

`The user/attacker can repay all of his debt, except letting remaining just a single unit of the asset`
FOR EXAMPLE  :
Like if user/attacker borrowed  `10e18`, then he can repay `999....(18 nines)`, which would leave 1 unit of asset as debt for his name, hence it won't cause any loss for him to implement this DOS.
And because of single unit of asset being present in the Pool, the withdrawing of all amount will revert, making force removal impossible.

Hence this functionality with the current implementation , can't be used, since it can easily be manipulated in situation to always revert.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> @z3s I didn't understand your response for invalidating this.
> 
> This has nothing to do with the number of depositors , whether there be only 1 or other.
> 
> This functionality of setting `forceRemove` as TRUE while calling `SuperPool::removePool` is itself might be added so that ` if in future any situation arises where the SuperPool owner has to remove a particular POOL`.
> 
> Then he can do, without causing any loss to the depositors , hence forcefully withdrawing all assets back to SuperPool from the given Base Pool
> 
> But considering current implementation, the functionality cannot be used, and a pool will never be able to removed with forceApprove = True, if there is even a single unit of assets that hasn't been repayed, since it will always REVERT as explained in REPORT.
> 
> Then the only option left would be removing pool with setting `forceRemove` as FALSE, which will not retreive the Assets in the Pool, and would just remove it , causing loss for SuperPool depositors.
> 
> `One mistake while writing in report from my side, that I have written if anyone borrows even a single unit of asset, then this issue can occur`, but a user can't borrow single unit of asset since there is a `minBorrow` check while borrowing.
> 
> But if this is the argument is centered around `minBorrow` check being already present, and user/attacker would has to lose funds from his side in order to perform this DOS , then :
> 
> `The user/attacker can repay all of his debt, except letting remaining just a single unit of the asset`
> FOR EXAMPLE  :
> Like if user/attacker borrowed  `10e18`, then he can repay `999....(18 nines)`, which would leave 1 unit of asset as debt for his name, hence it won't cause any loss for him to implement this DOS.
> And because of single unit of asset being present in the Pool, the withdrawing of all amount will revert, making force removal impossible.
> 
> Hence this functionality with the current implementation , can't be used, since it can easily be manipulated in situation to always revert.

You've deleted an escalation for this issue.

**Comment by Pranay-Bhilare** [comment]
Escalate

@z3s  I didn't understand your response for invalidating this.

This has nothing to do with the number of depositors , whether there be only 1 or other.

This functionality of setting `forceRemove` as TRUE while calling `SuperPool::removePool` is itself might be added so that ` if in future any situation arises where the SuperPool owner has to remove a particular POOL`.

Then he can do, without causing any loss to the depositors , hence forcefully withdrawing all assets back to SuperPool from the given Base Pool

But considering current implementation, the functionality cannot be used, and a pool will never be able to removed with forceApprove = True, if there is even a single unit of assets that hasn't been repayed, since it will always REVERT as explained in REPORT.

Then the only option left would be removing pool with setting `forceRemove` as FALSE, which will not retreive the Assets in the Pool, and would just remove it , causing loss for SuperPool depositors.

`One mistake while writing in report from my side, that I have written if anyone borrows even a single unit of asset, then this issue can occur`, but a user can't borrow single unit of asset since there is a `minBorrow` check while borrowing.

Instead, he can repay that much amount, which will keep his debt just above the minDebt, not causing much of a loss for him to DOS.

Hence this functionality with the current implementation , can't be used, since it can easily be manipulated in situation to always revert.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> @z3s  I didn't understand your response for invalidating this.
> 
> This has nothing to do with the number of depositors , whether there be only 1 or other.
> 
> This functionality of setting `forceRemove` as TRUE while calling `SuperPool::removePool` is itself might be added so that ` if in future any situation arises where the SuperPool owner has to remove a particular POOL`.
> 
> Then he can do, without causing any loss to the depositors , hence forcefully withdrawing all assets back to SuperPool from the given Base Pool
> 
> But considering current implementation, the functionality cannot be used, and a pool will never be able to removed with forceApprove = True, if there is even a single unit of assets that hasn't been repayed, since it will always REVERT as explained in REPORT.
> 
> Then the only option left would be removing pool with setting `forceRemove` as FALSE, which will not retreive the Assets in the Pool, and would just remove it , causing loss for SuperPool depositors.
> 
> `One mistake while writing in report from my side, that I have written if anyone borrows even a single unit of asset, then this issue can occur`, but a user can't borrow single unit of asset since there is a `minBorrow` check while borrowing.
> 
> Instead, he can repay that much amount, which will keep his debt just above the minDebt, not causing much of a loss for him to DOS.
> 
> Hence this functionality with the current implementation , can't be used, since it can easily be manipulated in situation to always revert.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I don't see a problem here. The owner can call `Pool.withdraw()` and then call `removePool()` with the parameter `forceRemove = false` before deciding to remove the pool.

The other option is to simply pause the `borrow()` function temporarily:

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/Pool.sol#L423
```solidity
if (pool.isPaused) revert Pool_PoolPaused(poolId);
```

Planning to reject the escalation and leave the issue as is.

**Comment by Pranay-Bhilare** [comment]
@cvetanovv Sir.
> I don't see a problem here. The owner can call Pool.withdraw() and then call removePool() with the parameter forceRemove = false before deciding to remove the pool.

The SuperPool Owner can't withdraw assets from a specific POOL-ID by calling `Pool.withdraw()`.

There can be only two ways if superPool owner wants to withdraw from a specific PoolID, and in both ways it will always revert.

1) If  `owner = SuperPool address`  is passed as parameter while calling `withdraw` function.
Here because of following implementation  :
```javascript
if (msg.sender != owner && !isOperator[owner][msg.sender]) {
            uint256 allowed = allowance[owner][msg.sender][poolId];
            if (allowed != type(uint256).max) allowance[owner][msg.sender][poolId] = allowed - shares;
        }
```
Here the msg.sender will be OWNER OF SUPERPOOL, and isOperator will check whether the caller is Operator or not 
There's no implementation currently , where the setOperator function of ERC6909 is being called and the SuperPool owner is set as the operator for SuperPool address.

Hence it will enter in the if block , and then the `allowed` value will be `0`, since currently there's no implementation where `increaseAllowance` of ERC6909 is being called to increase the allowance of SuperPool's owner for SuperPool address.
Hence further `if (allowed != type(uint256).max) allowance[owner][msg.sender][poolId] = allowed - shares;` will `revert` because of underflow.

2) If `owner = owner of SuperPool's address` is being passed as parameter.

Here it will revert because : 
```javascript
_burn(owner, poolId, shares);
```
The shares are being burnt, and for the SuperPool's owner, there will never ever be shares minted, since always it will be minted for SuperPool address.
Hence it will revert here also.

ALSO NOTE : There's no implementation to withdraw from a specific poolID currently.

Hence the owner can't withdraw from specific POOL-ID and then remove it using removePool , as you stated above

And regarding another point .

> The other option is to simply pause the borrow() function temporarily.

Only the owner of POOL-ID, can toggle the pausing functionality, not the SUPER POOL owner.

```javascript
function togglePause(uint256 poolId) external {
>>>        if (msg.sender != ownerOf[poolId]) revert Pool_OnlyPoolOwner(poolId, msg.sender);
        PoolData storage pool = poolDataFor[poolId];
        pool.isPaused = !pool.isPaused;
        emit PoolPauseToggled(poolId, pool.isPaused);
    }
```

**Comment by cvetanovv** [comment]
But the admin can still remove the pool. He will just set `forceRemove` to false, and he can use the function. We don't have broken functionality because the function works. Admin will be able to remove a pool.

The funds will be lost, but there is a rule in Sherlock docs in such cases when an admin needs to do an action that may harm users:

>An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.

Because of this rule, my decision to reject the escalation remains.

**Comment by Pranay-Bhilare** [comment]
@cvetanovv Sir would just like to clear things up constructively & if we can get sponsor's input on this issue would also help.

Wouldn't the issue situation & and Sherlock's rule situations be completely different ?

Like in rule , it feels like admin `INTENTIONALLY` break assumptions about functioning of code , and does actions which causes loss of funds and HARMS users
Whereas here, there would be `NO OTHER OPTION`, rather to remove a pool without withdrawing the funds from it , causing direct loss to users ??
Isn't this a broken functionality and `NOT An Admin Input/call validation` ??

This wouldn't be a choice of ADMIN, to act such way to cause HARM to users.
`ADMIN HERE IS NOT CAUSING ANY HARM TO USERS FROM HIS SIDE`
Rather he would not be having other option, because the `FUNCTIONALITY IS BROKEN`.
And because of system limitation, users will have loss of funds

Hence I think this wouldn't be a case which is based on validating the input/calling actions by ADMIN (rule stated)
I feel both are completely different situations.

If sponsors can give their view, how they think regarding this removing pool functionality, and this situation if it happens, would be a good help for concluding the discussion.

Thank you !

**Comment by cvetanovv** [comment]
This issue is that the function `removePool()` always reverts. But this is not true.

I quote the Impact, but the Title, Summary, and Details also state that the function "aways revert":
> SuperPool::removePool() function call will always revert if anyone borrow if 1 unit of asset.
> Because of which if SuperPool owner would have to remove the given pool due to any reason, he won't be able to remove it , until unless all borrow amounts are being repayed, which would be based on users only, and can't be in hands of protocol.

The entire issue is about the admin not being able to use `removePool()`. 

However, this is not true. We already discussed this, and the admin can call the function and remove a pool. We don't have broken functionality, and the admin can use the function.

My decision to reject the escalation remains.

**Comment by Pranay-Bhilare** [comment]
@cvetanovv Sir
In Summary : 
>it is expected to withdraw all assets being deposited by SuperPool in the given BasePool, which won't be able to happen.

In Details section : 
> This is because while removing it is being expected to withdraw all assets. But if anyone would have borrowed it, then all the assets would not be able to be withdrawn, and hence the removePool function call will always revert.

In Escalation for giving more clear context :
> Then the only option left would be removing pool with setting forceRemove as FALSE, which will not retreive the Assets in the Pool, and would just remove it , causing loss for SuperPool depositors.

>Hence this functionality with the current implementation , can't be used, since it can easily be manipulated in situation to always revert.

Regarding the impact you quoted, I am trying to explain that only.
IT CONTRADICTS THE EXPECTED FUNCTIONALITY by the protocol, that all funds/assets will be retrieved/withdrawn, but it won't happen, since it will `ALWAYS REVERT` in this case.  Because of this I have emphasised more on `ALWAYS REVERT`

> The entire issue is about the admin not being able to use removePool().

My entire issue is not regarding this sir.

The admin will not be able to use `removePool()` if expected to `forceRemove` and withdraw all assets. My whole issue revolves around this condition and case.

I have stated that it will `always revert` with a `CONDITION`, my title itself covers the CONDITION, that if `forceRemove` is `TRUE` & if anyone borrows from that basePool , then the admin will not be able to remove.

Ofcourse sir, if `forceRemove = false`, admin can remove the basePool, but I was not discussing regarding this case.

This is expected by the protocol, that for `forceRemove = TRUE` , it SHOULD withdraw all assets.
But this won't happen, since it will always revert for the `STATED CASE`.

And since, the FUNCTIONALITY expected by the protocol, will NOT happen, I stated that this might be broken functionality, that code will not work as being expected.

Apologies for my mistake to not write it again explicitly in the `IMPACT` section.  I thought it would directly convey what would be the impact, that this is expected, but this won't happen, hence it will cause this issue.
There might be issues in the explanation part from my side, I am constantly trying to improve my reporting skills

But this is what I was genuinely trying to convey & indicate, that

` SINCE IT WILL ALWAYS REVERT, ASSETS WILL NOT BEING ABLE TO WITHDRAW, EXPECTED FUNCTIONALITY WON'T WORK, AND ADMIN WOULD BE LEFT WITH ONLY OPTION TO REMOVE POOL WITHOUT WITHDRAWING THE ASSETS `

I sincerely request not to INVALIDATE my report because of this reason, and my explanation STYLE, because I was genuinely trying to indicate the same issue only, just the way was different.

And my whole issue was NOT about `ADMIN NOT BEING ABLE TO USE removePool()`,  as you stated above.

I have explained my side properly sir. I hope things work out fairly.
Apologies for poor explanation skills, constantly working on them.

Thank you !!

**Comment by cvetanovv** [comment]
@Pranay-Bhilare, I understand what you mean by your last comment. Maybe it really shouldn't be about the admin rule (trusted admin), but the function itself is not working as intended by the protocol.

My previous comments come from your wrong impact:
> SuperPool::removePool() function call will always revert if anyone borrow if 1 unit of asset. 
>Because of which if SuperPool owner would have to remove the given pool due to any reason, he won't be able to remove it , until unless all borrow amounts are being repayed, which would be based on users only, and can't be in hands of protocol.

This is also not true. The admin can use the function if he calls it with `forceRemove = false`.

But you have specified the correct impact elsewhere in the issue, and that is that the function does not work as intended.

```solidity
function removePool(uint256 poolId, bool forceRemove) external onlyOwner {
        if (poolCapFor[poolId] == 0) return; // no op if pool is not in queue
        uint256 assetsInPool = POOL.getAssetsOf(poolId, address(this));
        if (forceRemove && assetsInPool > 0) POOL.withdraw(poolId, assetsInPool, address(this), address(this));
        _removePool(poolId);
        poolCapFor[poolId] = 0;
        emit PoolCapSet(poolId, 0);
    }
```
The `removePool()` should have functionality with which the admin can choose whether to forcе remove the pool. But this doesn't work, as explained in the issue. 

That means we have broken core contract functionality.

I am planning to accept the escalation and make this issue Medium.

**Comment by samuraii77** [comment]
I believe this might be intended. If we take a look at the revert condition in `_removePool()`, we can see the following:
```solidity
if (POOL.getAssetsOf(poolId, address(this)) != 0) revert SuperPool_NonZeroPoolBalance(address(this), poolId);
```
We can see that removals should only be possible when assets are not 0. If we were to only withdraw what's available for us to withdraw in the pool (as suggested in the report and what is explained to be the mistake in the code), then we would always revert here anyway as that's not all of the assets we have so they wouldn't be equal to 0 in the check above. Furthermore, if we were to only withdraw what's available and we assume that this part wouldn't revert, then this would lead to stuck funds in the pool that we won't be able to withdraw which is critical. Also, it is very unlikely that we won't be able to withdraw all of the assets as chances are that the deposits of the Superpool into a particular pool would be less than 1%, thus the utilization ratio would have to be over 99% for us to actually revert in that part of the code.

**Comment by Pranay-Bhilare** [comment]
The recommendation mitigation might not be correct, and I acknowledge that, as I myself was not able to come up with a good solution & because of time constraint, hence stated that only which is available for withdraw should be initiated. Which will again cause stucking of remaining funds that we won't be able withdraw again, which is correct, and hence would not be a good mitigiation.

The mitigation part should be looked into carefully.

But regarding the revert condition :
```javascript
if (POOL.getAssetsOf(poolId, address(this)) != 0) revert SuperPool_NonZeroPoolBalance(address(this), poolId);
```
This is not the revert which I have discussed on in the issue, this is different.
And I believe this was added to check whether all the funds have been withdrawn or NOT.
Since the protocol is intending & expecting to withdraw all of the funds , if thinking to `forceRemove` it.

But that's what the issues states, that , what's expected will not HAPPEN, if anyone `borrows` from that basePOOL.

> Also, it is very unlikely that we won't be able to withdraw all of the assets as chances are that the deposits of the Superpool into a particular pool would be less than 1%, thus the utilization ratio would have to be over 99% for us to actually revert in that part of the code.

If I am understanding this correctly, it is not fixed that deposits into a particular pool would be less than 1%.

If we see depositing implementation, when `_supplyToPools` is called, then the pools in `depositQueue` are being added, and first pool in  deposit pool is filled completely till the pool cap.

So less than 1 % will be deposit amount is not TRUE. It is not fixed and known, and can vary on number of base pools, and order of them present in `depositQueue`.

And the utilization ratio hasn't to be > 99% to revert, if I am understanding correctly what you mean.
Even if 1 unit asset is being borrowed, still it would revert as explained in issue

**Comment by Nihavent** [comment]
If I understand this report correctly it is a non-issue. Please correct me if I am misunderstanding something.

The issue can be summarized simply:
1. Pool withdrawals revert if the pool doesn't have enough liqudiity to service the withdrawal amount
2. Therefore, if `SuperPoool::removePool()` is called with `forceRemove = true' and there is not enough liquidity to service the full withdrawal of the SuperPool's assets from the base pool being removed, the call will revert.

This is not a DOS, this is how lending pools work, how could the base pool possibly pay out a withdrawal request which exceeds the available liquidity?


- It is not generally true to say that 'totalBorrowAssets > 0' in the underlying pool is a pre-condition for this revert. 
  - The edge case where this statement is true is when a SuperPool is the only supplier to an underlying pool (this was the example given in the report). 
    - And in such cases, this is like saying "if there is a sole supplier for a given base pool and there is a non-zero amount borrowed from that pool, then the supplier cannot withdraw their entire deposit". Well of course they can't, because some of their loaned funds are currently borrowed. They need to wait for a repayment or a deposit so that the pool has enough liquidity to service their full withdrawal.

- It is generally true to say that if the available liquidity in the underlying pool (totalSupplyAssets - totalBorrowAssets) is less than the requested withdrawal amount then the withdrawal will fail.
    - This statement is true for all pool suppliers including SuperPools.

This issue has the same root cause as numerous other invalid issues relating to high utilization/low liquidity in base pools, I'll link a few that are easy to find, note they all point out different impacts but the root cause is the same (withdrawal disabled when insufficient liquidity)

- https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/101
- https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/127
- https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/175
- https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/273
- https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/583 (exactly the same issue)

**Comment by Pranay-Bhilare** [comment]
Yes, I have also explained same only ( My explanation style is bad, working on improving it).

The main problem is that what’s expected from the protocol won’t happen.

` Protocol has added a functionality for SuperPool owners to forcefully remove a basePool, and withdraw all assets present in it by setting forceRemove = true while removePool(). But this expected and intended functionality/behaviour won't work, because of the following reasons. `

The reason which has been discussed ( by you also )

So the issue is not about illiquidity, high utilization/low liquidity OR regarding `liquidity constraints`.

It is regarding a functionality not working as intended & expected, as stated by judge also while validating

**Comment by Nihavent** [comment]
>"Protocol has added a functionality for SuperPool owners to forcefully remove a basePool, and withdraw all assets present in it by setting forceRemove = true while removePool(). But this expected and intended functionality/behaviour won't work, because of the following reasons.
>
>The reason which has been discussed ( by you also )
>
>So the issue is not about illiquidity, high utilization/low liquidity OR regarding liquidity constraints."

I believe you are confusing root cause with impact. 

You said the issue is about functionality of removePool() broken when forceRemove = true, this is the impact. When we ask why this impact occurs, we see this is due to a lack of liquidity in the base pool.

Therefore the root cause is due to illiquidity in the underlying pool.

By the way the same argument could be made for broken functionality in `Pool::withdraw()`:  "The Pool contract has added functionality to withdraw funds, however this is sometimes broken" (due to a temporary lack of liquidity).

Also `SuperPool::redeem()`:  "The SuperPool contract has added functionality for users to redeem shares for assets, however this is sometimes broken" (due to a temporary lack of liquidity).

I hope you can see these are all examples of impacts, with the same root cause.

Due to design, the underlying pool cannot make any guarantees about availability of withdrawals. This is a risk taken by suppliers, that sometimes lots of funds are borrowed and they cannot withdraw.

**Comment by Pranay-Bhilare** [comment]
Ohh, okay I understand.
Yes you are correct. And those examples are also correct, which is the same root cause here.

Ofcourse if you don't have enough liquidity , then you can't redeem/withdraw. That's just straight facts.

But if we see here. 
It's the PROTOCOL's expectation and intention and they have implemented code such way, that all the funds should be retrieved back. 
Its how they have designed it. But ofcourse if there would be illiquidity, even of 1 unit of asset, this can't happen.

So that's what I am also saying, that what PROTOCOL expects will not happen.

Your points are all correct. That its root cause is illiquidity, and of course if you will do any course of withdrawal , if there's not enough liquidity, you won't be able to withdraw.

But its not about availability of withdrawals, but rather the designed feature/functionality they are providing, to force removing a base pool in the intended/expected manner by the protocol.

The protocol has implemented such way , that withdraws all assets. `THEY` are expecting full liquidity returns.
Its their way of implemented, and that's what we are pointing out to, that this implementation from their side is flawed.

You can't withdraw all assets, hence can't `FORCE REMOVE` any pool, as expected, if any sort of even minor illiquidity is their, how could you ? Just the way you are also saying. And hence you can't.

But the protocol is expecting you can, and we are saying you can't.

And hence the admin would be left with just removing pool without `forceRemove`, where no funds would be retrieved back, and pool will be removed, hence causing loss also. Hence they should look into this .
 
I hope I was able to explain how this protocol's implementation/expectation issue is different from the general liquidity issues examples you are stating.

**Comment by Nihavent** [comment]
I still believe you’re talking about a specific impact of a pool that lacks liquidity to service the full withdrawal. I won’t labour that point any more though. 

>” It's the PROTOCOL's expectation and intention and they have implemented code such way, that all the funds should be retrieved back.
It’s how they have designed it. But ofcourse if there would be illiquidity, even of 1 unit of asset, this can't happen.”


I don’t believe it’s fair to say the protocol expects a full withdrawal from a pool that doesn’t have enough liquidity. 

It seems objective and fair to say that the ‘forceremove’ argument was included in this function as a matter of convenience to withdraw and remove a pool in 1 call. 
I don’t believe it’s fair and objective to assert that the ‘forceremove’ argument should enable withdrawals when there is an underlying reason why they can’t succeeds (insufficient liquidity). 

As previously mentioned by the HOJ the pool removal can be ‘forced’ by not withdrawing all assets. 

I have nothing further to add to this, much respect and good luck. I would kindly ask that the above issues be duplicated if this issue ends up being validated as we are now in agreement they share the same root cause.

**Comment by Pranay-Bhilare** [comment]
I'll leave it to HOJ with due respect regarding this issue, have had a lot of back and forth discussion, at the end all depends on HOJ itself. 
With due respect, good luck. Thanks !

**Comment by ruvaag** [comment]
I don't believe this should be a valid issue.

The description conflates illiquidity with a DoS. As a counter example –– this scenario should not occur if the superpool has a very small deposit in the underlying such that the `Pool.withdraw()` call succeeds even with existing borrows

My suggestion would be to mark this as a low, and the actual finding be that "forceRemove does not guarantee removal due to potential illiquidity". The fix will be to simply rename the `forceRemove` param to something more indicative of it's behavior

**Comment by cvetanovv** [comment]
From the sponsor's comment, it's clear that the issue is less severe than it might initially appear. The primary source of confusion lies in the interpretation of the `forceRemove` parameter. The parameter is not designed to guarantee pool removal under all conditions, particularly when there is insufficient liquidity.

My decision is to reject the escalation.

**Comment by Pranay-Bhilare** [comment]
@ruvaag  @cvetanovv  Respectfully , wanted to clear something related to the counter example being provided by the sponsor.

The provided counter example situation would only be TRUE , if someone deposits into the POOL not through SuperPool, instead directly from Pool.sol , and only a small amount (as stated) would be deposited through SuperPool.

And according to the docs : 
> For users accessing the platform via the Sentiment UI, interaction with Base Pools is indirect, typically through Super Pools that efficiently distribute user liquidity across multiple Base Pools for enhanced liquidity management.

> If users interact with Sentiment via the Sentiment UI, it is unlikely that they will be interacting with Base Pools themselves. Instead they will likely be depositing into a Super Pool, which distributes their liquidity among several Base Pools.

So mainly, on traditional basis it is being expected that deposits would be done, via Sentiment UI , hence via SuperPool only.
 
And if all deposits in that underlying pool is being done through SuperPool only, as expected , then the counter example provided by sponsor will NOT be TRUE.

As then tracking would be done on basis of `getAssetsOf[SuperPool][PoolID]` only. And every time if any even minimal borrow would be there, then `maxWithdrawalAssets < assets` will always be TRUE, hence will always revert.

> The fix will be to simply rename the forceRemove param to something more indicative of it's behavior.

> The primary source of confusion lies in the interpretation of the forceRemove parameter.

I believe it not about renaming the parameter, & it not how its interpreted.

According to the code, it is designed & implemented such way to withdraw all assets that were deposited by SuperPool in that basePool.
And the implementation won't work, if illiquidity is there.

> The parameter is not designed to guarantee pool removal under all conditions, particularly when there is insufficient liquidity.

That's what the issue is.

As said in report , it can be manipulated easily into this illiquidity state with minimal amount.
Which would make this implementation revert always.

And if ever wanted to remove pool, admin will not be left with any other choice rather to remove without withdrawing the assets if such situation arises.

Respectfully @cvetanovv , kindly recheck again regarding this issue, with above considered points I have provided.

Apologies as this is taking a lot back & forth discuss, probably frustrating too, but I am sharing & stating what I believe is true.
Surely would respectfully accept in what the Judge thinks is correct , after explaining everything from my side.

But I believe, just once should be reviewed again, after the points being put above.

Thank you !!

**Comment by cvetanovv** [comment]
My decision to be invalid remains. There are two main reasons: 

- This issue falls under the "Admin Input/call validation": An admin action can break certain assumptions about the functioning of the code.
- The other reason is that we don't have broken functionality, and the sponsor confirmed it.

My decision to reject the escalation remains.

**Comment by Pranay-Bhilare** [comment]
@cvetanovv Sir we did discussed above that this is not admin input call validation issue , you agreed too.
Still now this as reason of invalidation ?

Regarding sponsor's comment and counter part, I shared every reason how it is not true and shared that how it is not regarding general illiquidity .

Can I please know why these points were not being addressed ??

And if a state can be so easily achieved by anyone manipulating it , leading it to not be able to use a functionality and also leading to loss of funds, is not an issue?

The implementation/logic of withdrawing all assets while removing a basePool can be easily manipulate to a bad state to always revert.
How come this is not an issue ??

Respectfully asking sir. 

 Any explanation that I can get to understand the situation and not addressing the points.
 Also regarding the 1st reason you gave to invalidate , which was being agreed that its not admin input/call validation issue.

Would be really helpful sir.
Kindly requesting.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Pranay-Bhilare](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/455/#issuecomment-2352224772): rejected
