### ISSUE TITLE
Rea - Fee Configuration Issue

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-sentiment-v2-judging#515]
Rea

High

# Fee Configuration Issue

High

## Summary
The requestFeeUpdate function allows for a fee to be set by the owner, but it only validates if the fee is over 100% (1e18). A malicious owner could set an extremely high fee just under 100%, effectively stealing all earnings from pool.

## Vulnerability Detail
An attacker, potentially the contract owner or someone who gains control over the owner's account, sets the fee close to 100%. This would cause all interest earned by the pool to be redirected to the attacker. Users would receive no returns or even lose their principal due to hidden fees.

## Impact
Loss of all interest earnings for users, potentially millions in value depending on the pool size 

## Code Snippet

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/SuperPool.sol#L366

## Tool used
Manual Review

## Recommendation
Implement a hard cap on fees(e.g., 10%) and add a governance or multisig mechanism to approve fee charges, reducing the risk of a single-point attack

Duplicate of #440

**Comment by serial-coder** [comment]
Escalate

Hi @z3s,

This issue is invalid as it does not state the vulnerability regarding the "incorrect validation" (i.e., must use `_fee` (function param) instead of the `fee` (state variable)).

In other words, this issue states that an owner can set "an extremely high fee just under 100%", which is an intended design confirmed by the sponsor in the public channel.

Thanks for your time.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Hi @z3s,
> 
> This issue is invalid as it does not state the vulnerability regarding the "incorrect validation" (i.e., must use `_fee` (function param) instead of the `fee` (state variable)).
> 
> In other words, this issue states that an owner can set "an extremely high fee just under 100%", which is an intended design confirmed by the sponsor in the public channel.
> 
> Thanks for your time.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by serial-coder** [comment]
*I cannot escalate the issue due to insufficient escalation threshold*

Hi @z3s,

This issue is invalid as it does not state the vulnerability regarding the "incorrect validation" (i.e., must use `_fee` (function param) instead of the `fee` (state variable)).

In other words, this issue states that an owner can set "an extremely high fee just under 100%", which is an intended design confirmed by the sponsor in the public channel.

Thanks for your time.
