### ISSUE TITLE
KupiaSec - Rounding Error in Calculating `newBorrowAssets` during borrow/repayment

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-08-sentiment-v2-judging#529]
KupiaSec

Medium

# Rounding Error in Calculating `newBorrowAssets` during borrow/repayment

## Summary
During the borrow/repayment operation in the pool, a rounding error arises when calculating `newBorrowAssets`, causing it to mismatch with the amount returned by `getBorrowsOf`, which I believe should align.

## Vulnerability Detail
`newBorrowAssets` is meant to indicate the entire debt associated with a position, capturing the total amount of assets required to fully repay the debt obligation.
I believe it should match the value given by getBorrowsOf, assuming that a repayment could occur immediately without any interest having accrued. Nevertheless, due to differences in the rounding directions used in these calculations, inconsistencies can occur.

As a consequence, even a small discrepancy might lead to `newBorrowAssets` falling below `minDebt`, which in turn can trigger the transaction to revert with the `Pool_DebtTooLow` error.

In `borrow` function, it used Math.Rounding.Down:
```solidity
    function borrow(uint256 poolId, address position, uint256 amt) external returns (uint256 borrowShares) {
        ...
        uint256 newBorrowAssets = _convertToAssets(
            borrowSharesOf[poolId][position] + borrowShares,
            pool.totalBorrowAssets + amt,
            pool.totalBorrowShares + borrowShares,
>           Math.Rounding.Down
        );
        if (_getValueOf(pool.asset, newBorrowAssets) < minDebt) {
            revert Pool_DebtTooLow(poolId, pool.asset, newBorrowAssets);
        }
```
In `getBorrowsOf` function, it used Math.Rounding.Up:
```solidity
    function getBorrowsOf(uint256 poolId, address position) public view returns (uint256) {
        PoolData storage pool = poolDataFor[poolId];
        (uint256 accruedInterest,) = simulateAccrue(pool);
        // [ROUND] round up to enable enable complete debt repayment
        return _convertToAssets(
            borrowSharesOf[poolId][position],
            pool.totalBorrowAssets + accruedInterest,
            pool.totalBorrowShares,
>            Math.Rounding.Up
        );
    }
```

Same happens in `repay` function:
```solidity
    function repay(uint256 poolId, address position, uint256 amt) external returns (uint256 remainingShares) {
        ...
        remainingShares = borrowSharesOf[poolId][position] - borrowShares;
        if (remainingShares > 0) {
            uint256 newBorrowAssets = _convertToAssets(
>               remainingShares, pool.totalBorrowAssets - amt, pool.totalBorrowShares - borrowShares, Math.Rounding.Down
            );
            if (_getValueOf(pool.asset, newBorrowAssets) < minDebt) {
                revert Pool_DebtTooLow(poolId, pool.asset, newBorrowAssets);
            }
        }
```

## Impact
This represents a notable instance of a `rounding error`, and although it is not a frequent occurrence, it can cause borrow or repay operations to unjustly revert with the `Pool_DebtTooLow` error.

## Code Snippet
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L450

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L238

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/main/protocol-v2/src/Pool.sol#L509

## Tool used
Manual Review

## Recommendation
Adjust the rounding method to `Math.Rounding.Up` when calculating `newBorrowAssets`.

In `borrow` function:
```diff
    function borrow(uint256 poolId, address position, uint256 amt) external returns (uint256 borrowShares) {
        ...
        uint256 newBorrowAssets = _convertToAssets(
            borrowSharesOf[poolId][position] + borrowShares,
            pool.totalBorrowAssets + amt,
            pool.totalBorrowShares + borrowShares,
-           Math.Rounding.Down
+           Math.Rounding.Up
        );
        if (_getValueOf(pool.asset, newBorrowAssets) < minDebt) {
            revert Pool_DebtTooLow(poolId, pool.asset, newBorrowAssets);
        }
```

In `repay` function:
```diff
    function repay(uint256 poolId, address position, uint256 amt) external returns (uint256 remainingShares) {
        ...
        remainingShares = borrowSharesOf[poolId][position] - borrowShares;
        if (remainingShares > 0) {
            uint256 newBorrowAssets = _convertToAssets(
-               remainingShares, pool.totalBorrowAssets - amt, pool.totalBorrowShares - borrowShares, Math.Rounding.Down
+               remainingShares, pool.totalBorrowAssets - amt, pool.totalBorrowShares - borrowShares, Math.Rounding.Up
            );
            if (_getValueOf(pool.asset, newBorrowAssets) < minDebt) {
                revert Pool_DebtTooLow(poolId, pool.asset, newBorrowAssets);
            }
        }
```

**Comment by S3v3ru5** [comment]
I am not sure of the value between `getBorrowsOf` and the `newBorrowAssets`. 

I do not understand the impact clearly.

In borrow function, newBorrowAssets are rounded-down value of `borrowedShares` => `newBorrowAssets <= amt`.

By ensuring `newBorrowAssets >= minDebt` they are also ensuring `amt > minDebt`.
By setting `amt` such that debt is `minDebt`, users can borrow `amt` tokens. There is no unjust revert, it reverts only if `amt` value is less than `minDebt` which it should.

Also, If `newBorrowAssets` is rounded-up then `newBorrowAssets >= amt` then checking `newBorrowAssets >= minDebt` does not ensure `amt > minDebt`. So user can borrow `amt` whose value is less than `minDebt`.

The protocol is correctly `rounding-down`. `Rounding-up` leads to other issues.

Contract should check against smallest value(round-down) when verifying lower bounds and should check against maximum value(round-up) when verifying upper bound.

The protocol is verifying the lower-bound so the implementation is correct and this is not a valid issue.

**Comment by NicolaMirchev** [comment]
Escalate as per above comment.

**Comment by sherlock-admin3** [comment]
> Escalate as per above comment.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by KupiaSecAdmin** [comment]
@S3v3ru5

Regarding the previous comment: `I am not sure of the value between getBorrowsOf and newBorrowAssets` - these values are indeed interconnected and should match, assuming no interest has accrued at that specific time.
As highlighted in the vulnerability details, `getBorrowsOf` is intended to represent the total debt linked to a position, encompassing the full amount of assets needed to completely settle the debt obligation.

Additionally, with reference to the comment: `By ensuring newBorrowAssets >= minDebt, they are also ensuring amt > minDebt,` - this helps clarify conditional consequences within a specific borrowing or repayment process.
The core of this issue lies in the rounding mismatch between the two functions `getBorrowsOf` and `borrow/repay`. This discrepancy results in a clear fault, causing a revert with `Pool_DebtTooLow`, marking it as a significant instance of rounding error.

**Comment by cvetanovv** [comment]
I agree that this mismatch can lead to a revert of `borrow()` and `repay()`, but I'm not sure if the impact is sufficient for Medium severity.

@z3s What do you think?

**Comment by KupiaSecAdmin** [comment]
@cvetanovv 
Thanks a lot for checking the comments.

I believe the impact is sufficient enough to be a *medium severity* as
- it can break borrow and repay operations which are the *core functionalities* of the protocol
- it's clearly mentioned that `Stack precision errors and/or incorrect rounding direction` would be considered one of the main vulnerability vectors in contest documentation.

**Comment by ruvaag** [comment]
I think this should be invalid, because the impact, severity and likelihood is unclear.

`newBorrowAssets` is never stored, and only used for minimum debt checks. It is not meant to be used as a persistent value of 'remaining debt' as suggested by OP.

I think a real issue would've been if the value returned by `getBorrowOf` and amount settled by `repay` are mismatched, leading to reverts or miscalculation. None of which seem to be the case here.

**Comment by KupiaSecAdmin** [comment]
It's exactly what this issue represents. Due to the rounding mismatch in `getBorrowsOf` and `repay` function, it returns different values of `newBorrowAssets` despite being calculated on same shares.
It doesn't matter if we stored `newBorrowAssets` or not, because it only comes up after borrow/repay operation and calculated based on latter share value.

The likelihood is as clear as I quoted in above comment and I believe it clearly falls under medium severity. Though it embraces  some certain situation of position balance evolving around low debt limit, it'd be pretty common case as the users would be willing to seek chances to survive just over limit for the sake of trading or arbitrage etc.

**Comment by KupiaSecAdmin** [comment]
> I think a real issue would've been if the value returned by `getBorrowOf` and amount settled by `repay` are mismatched, leading to reverts or miscalculation. None of which seem to be the case here.

It's exactly what this issue represents. Due to the rounding mismatch in getBorrowsOf and repay function, it returns different values of newBorrowAssets despite being calculated on same shares.
It doesn't matter if we stored newBorrowAssets or not, because it only comes up after borrow/repay operation and calculated based on latter share value.

The likelihood is as clear as I quoted in above comment and I believe it clearly falls under medium severity. Though it embraces some certain situation of position balance evolving around low debt limit, it'd be pretty common case as the users would be willing to seek chances to survive just over limit for the sake of trading or arbitrage etc.

**Comment by cvetanovv** [comment]
The current rounding strategy in the `borrow()` and `repay()` functions are inconsistent with `getBorrowsOf()`. 

This mismatch can result in operations near low debt limits reverting due to a miscalculation, where the amount is perceived as being below the `minDebt` threshold. Although the user should meet the debt requirement, this inconsistency creates unjust reverts, disrupting core borrow and repay functionality.

Planning to reject the escalation and leave the issue as is.

**Comment by samuraii77** [comment]
According to the rules, issues about rounding should include a POC. I think it would be fair for the watson to provide a POC showcasing exactly how the issue can arise and its impact.

**Comment by cvetanovv** [comment]
@samuraii is right that this type of issue needs PoC. In this case, the sponsor confirmed that there is a mismatch that leads to a revert. That's why I made this decision without PoC.

**Comment by samuraii77** [comment]
It seems to me that he said the issue should be invalid unless you had a chat with him outside of this discussion or I am misinterpreting his comment.

**Comment by cvetanovv** [comment]
@KupiaSecAdmin Can you provide a PoC to prove the revert is happening?

**Comment by KupiaSecAdmin** [comment]
Sure @cvetanovv, I'd love to.

This could be a scenario where an unfair revert arises in `repay` function.

1. Sam borrowed assets worth 2*minDebt in value.
2. He wants to repay `XXX` assets worth minDebt in value, likely half of what he gets via `getBorrowsOf` function.
3. However, this `repay` function would revert because the function calculates `newBorrowAssets` with `Rounding.DOWN` while `getBorrowsOf` returned the asset amount with `Rounding.UP`. This rounding difference leads to difference in amount between `XXX` (what Sam expected to keep) and `newBorrowAssets` (calculated in `repay` function). Since the value of `XXX` was minDebt, `newBorrowAssets` would be lower than minDebt which would then causes unfair revert. Sam would surely be shocked.

While above PoC hypothetically explains the revert scenario in a specific situation, I believe it provides enough evidence on the rounding issue and corresponding reverts.
Thank you for your time!

Lastly I want to thank @samuraii77 for your huge effort to verify the validity of this issue highlighting his faith to "fairness and rules". Wish him good luck with future contests.

**Comment by S3v3ru5** [comment]
I'm going to repeat what I said in the first comment with an example.

The root cause mentioned in the issue is 

- "`newBorrowAssets` are incorrectly rounded down when compared to minDebt".

I believe this is intended for the following reason.

Protocol invariant: A position should have `0` value debt or **AT-LEAST** `minDebt` value.

Let's say `minDebt` is `155` then the value of borrow shares should be `0` or `>= 155`. The position debt could be `155`, `156`, `157`, .... but it should not be less than `< 155`.

This is the protocol invariant which should be preserved by the code.

Consider above scenario with example:

A user has repaid part of the debt. In the repay function, remaining debt (`newBorrowAssets`) is calculated (i.e the value of remaining borrow shares).

Let the exact value of remaining debt is `154.7` before doing any rounding.

Now the question is should the code round-down or round-up for comparison with `minDebt`?

The code currently rounds-down and this report says that its an issue. It is not an issue, this is the correct implementation.

- If code rounds up then
    - `154.7` becomes `155` >= minDebt. The repay function succeeds. the value `154.7` < `minDebt`  but rounding up has made the code accept it. This is violating the above protocol invariant.
- if code rounds down then
    - `154.7` becomes `154` < minDebt (155). The repay function fails because the position debt does not meet the `minDebt` requirement.  This is preserving the protocol invariant.


The main reason  for rounding-down is the **at-least** comparison with minDebt.

My first comment explains the same without an example.

Another argument is regarding the relation between `getBorrowsOf` and `newBorrowAssets`.

- `getBorrowsOf`: Value of borrow shares **user  have to pay to the protocol**. round-up otherwise protocol incurs the loss. In the above case if this rounds down, then user only have to pay `154` and protocol loses `0.7`.
- `newBorrowAssets`: Value of borrow shares **to be used for at-least minDebt comparison**. Round-down, otherwise protocol accepts values which are not atleast `minDebt`. In the above case, if it rounds-up then protocol accepts `154.7` as valid when its less than `minDebt = 155` i.e its not atleast minDebt.

The purpose of both values are different and the code uses the correct rounding direction for the required purpose: 
- `getBorrowsOf`: Value of borrow shares **user  have to pay to the protocol**. Code rounds-up
- `newBorrowAssets`: Value of borrow shares **to be used for at-least minDebt comparison**. Code rounds-down

**Comment by KupiaSecAdmin** [comment]
I appreciate above good points, @S3v3ru5!

Which value is used to compare the position debt ( either Rounding.DOWN or Rounding.UP ) is decided by protocol. It's also correct that protocol may face tiny loss due if the direction is UP as it allows the rounded-up gap amount.
As I've emphasized, `getBorrowsOf` function represents the debt amount user owes to the protocol and it should be rounded in the same direction as of `newBorrowAssets`. Whatever it is rounded down or up, user would accept it as his own debt through the function and plans his next movement and they deserve that.
But this isn't the case right now and it lets the protocol lose its transparency and enforces a repelling experience for users.

The finding was proposed as the contest held `rounding direction` as one of main vulnerability vectors though the situation would seem uncommon and financial loss could be small.

Up to now, I believe we've been through enough arguments with extra explainations and PoC provided. I respect the decision of judge on this matter and leave it to them from here.

**Comment by cvetanovv** [comment]
Even if there is a mismatch between `borrow()` and `repay()` and `getBorrowsOf()`, the impact is not enough for Medium severity. 

The fact that `borrow()` and `repay()` have some possibility of reverting in certain situations doesn't mean that they should be medium severity. The impact is insufficient. And there are too many uncertainties about whether they would revert.
The users can call them again with new values.

Planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [EgisSecurity](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/529/#issuecomment-2352463538): accepted
