### ISSUE TITLE
dimah7 - Crutial operations like borrowing/repaying will not work on Polygon

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-08-sentiment-v2-judging#550]
dimah7

Medium

# Crutial operations like borrowing/repaying will not work on Polygon

## Summary

In contest's README it's stated that the contracts will be deployed on: "Any EVM-compatbile network". However the protocol will not work on every EVM-compatible chain. More specifically all the chains which don't have the sequencer upfeed or available price feeds, in the project's context - Polygon

The protocol uses 3 kind of oracles, Chainlink, RedStone and a custom made fixed price oracle. However an issue can occur when retrieving the prices of assets, when the contracts are deployed on Polygon. Explained more detailly in the below section.

## Vulnerability Detail

When users try to borrow or repay assets, constantly the `_getValueOf` function is called to retrieve the needed prices from a particular oracle set by the RiskEngine: 

```javascript
function _getValueOf(address asset, uint256 amt) internal view returns (uint256) {
        address oracle = RiskEngine(riskEngine).getOracleFor(asset);
        return IOracle(oracle).getValueInEth(asset, amt);
    }
```

However there are few considerations not taken of concern: 

1. On the Chainlink oracles, a check is made to ensure some L2 chains sequencer is up: 

```javascript
function _checkSequencerFeed() private view {
        (, int256 answer, uint256 startedAt,,) = ARB_SEQ_FEED.latestRoundData();

        // answer == 0 -> sequncer up
        // answer == 1 -> sequencer down
        if (answer != 0) revert ChainlinkEthOracle_SequencerDown();
        if (startedAt == 0) revert ChainlinkEthOracle_InvalidRound();

        if (block.timestamp - startedAt <= SEQ_GRACE_PERIOD) revert ChainlinkEthOracle_GracePeriodNotOver();
    }
```

The problem is that, this function is revoked everytime when `getValueInEth()` is called: 

```javascript
function getValueInEth(address asset, uint256 amt) external view returns (uint256) {
        _checkSequencerFeed();

        // [ROUND] price is rounded down. this is used for both debt and asset math, neutral effect.
        return amt.mulDiv(_getPriceWithSanityChecks(asset), (10 ** IERC20Metadata(asset).decimals()));
    }
```

But the sequencer uptime feed is not available on Polygon per Chainlink [docs](https://docs.chain.link/data-feeds/l2-sequencer-feeds#available-networks), and since the uptime feed address is set in the constructor, means it can't be changed: 

```javascript
 constructor(address owner, address arbSeqFeed) Ownable() {
        ARB_SEQ_FEED = IAggegregatorV3(arbSeqFeed);
```

The prices can't be retrieved and the users can't interact with the borrow/repay functions, which beats the purpose of the protocol.

2. On the RedStone oracle, as per their [docs](https://docs.redstone.finance/docs/get-started/price-feeds#available-on-chain-classic-model), currently there are not available price feeds for Polygon chain, so the impact will be the same as above.

## Impact

1. If Chainlink oracles are set in Polygon: even if the sequencer feed is set to an address from the supported networks in the constructor, if the sequencer goes down on the available chain, that means users can't retrieve prices on Polygon also, which is not an option
2. Even if the RedStone oracle is set for Polygon: since there are not available feeds, implementing the fixed price oracle as default one for Polygon is also not an option since the price there is also `immutable`, but the prices of the assets are esentially fluctuating

- Impact: High, as described above oracles functionality will be completely bricked on Polygon, thus bricking the borrow/repay functions also
- Likelihood: Low, as it requires a deployment to Polygon L2
- Overall: Medium

## Code Snippet

https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/oracle/ChainlinkEthOracle.sol#L58-L59
https://github.com/sherlock-audit/2024-08-sentiment-v2/blob/0b472f4bffdb2c7432a5d21f1636139cc01561a5/protocol-v2/src/oracle/ChainlinkEthOracle.sol#L67-L68

## Tool used

Manual Review

## Recommendation

The oracle logic will function properly on the Chainlink oracles, if there is no check for the sequencer. So i would suggest to implement a function which is retrieving the chain id:

```javascript
uint256 public chainid;

function()... {
    assembly {
        chainid := chainid()
}
```

Upon revoking the `getValueInEth()` function first check if the chain id is the same as Polygon's, if there is a match skip the sequencer feed check, in order to prevent the reverts

**Comment by InfectedIsm** [comment]
Escalate

On behalf of dimah7

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> On behalf of dimah7

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Blngogo** [comment]
I think this should be a valid finding. The README states that the protocol will be deployed on any EVM-chain. This report describes that by current design, oracles will not be compatible on Polygon, as can be seen in the provided links. Thus bricking all the services which involve price retrievement, like lending or borrowing, which are the core functionalities.

**Comment by cvetanovv** [comment]
@ruvaag, what do you think about this issue? As far as I understand from the Readme, you are only interested in sequencer issues if they result in a loss of funds.

>If the codebase is to be deployed on an L2, what should be the behavior of the protocol in case of sequencer issues (if applicable)? Should Sherlock assume that the Sequencer won't misbehave, including going offline?
> - Issues due to sequencer going offline are valid only if they lead to a loss of funds and are not connected to price change risks. Auditors can assume the sequencer is not overtly malicious.

**Comment by Blngogo** [comment]
@cvetanovv Hello sir, just to point out that this report is not connected with sequencer issue. In this case it doesn't matter if the sequencer will be down or up. The report describes that oracles can't be integrated, if there will be deployment on Polygon, overall it's focusing on that oracles will not work on Polygon, subsequently borrow/repay can't be invoked. The README says that there will be deployment on every EVM-compatible chain. 

```
On what chains are the smart contracts going to be deployed?

Any EVM-compatbile network
```
If we take Polygon as example.

The problem is that everytime the core functions borrow/repay are called, it will try to retrieve prices but will check for sequencer uptime before that. However uptime feeds are `NOT AVAILABLE` on Polygon per Chainlink [docs](https://docs.chain.link/data-feeds/l2-sequencer-feeds#available-networks). And as per RedStone's [docs](https://docs.redstone.finance/docs/get-started/price-feeds#available-on-chain-classic-model) currently there are not price feeds available for Polygon. So basically borrow/repay can never be called, this beats the purpose of the project. However there are available price feeds on Chainlink for this chain, but sequencer up check must be skipped in order to retrieve them successfully, as the report recommends.

**Comment by cvetanovv** [comment]
After consulting with the HoJ it became clear that in order for this issue to be valid, it must be specified in the Readme that it will be deployed to the Polygon network(or other specific network).

It is currently written that it will be deployed on `Any EVM-compatbile network`. 

This is exactly why we have a custom oracle. The protocol will be deployed on many networks, and where Chainlink or RedStone Oracle is not working, custom Oracle will be used. 

Also, the main impact of the issue is that `borrowing/repaying` and similar functions will not work. But this is not true, and they will use a custom oracle. 

You can see that the sponsor also disagrees that we have a problem here by putting "Disputed" and "Won't fix" labels because there is nothing to fix. All the functions will continue to work without reverting.

Planning to reject the escalation and leave the issue as is.

**Comment by Blngogo** [comment]
@cvetanovv The README clearly says `Any EVM-compatible network`, which means any evm-compatible network. Now what HoJ states that in order this to be valid, specific networks must be mentioned is something new and it ovewrites the rules. By Sherlock's HoT, it's taken of concern what's mentioned in the README, and it's stated there `any evm network`, that's why these kind of questions are asked, to be able to specify your answers. Otherwise what's the point to have them? We are focusing our reports based on what's given in the README, because this sits above all the rules. Also i don't know if the sponsors dispution can be of so big importance, as judging here should not be influenced on this sir, as an example i can give half of the validated issues for this particular contest where sponsor states that will not fix, another example would be the valid min/max price reports, which is mainly 
validated based on Sherlock rules, the same should apply here also.

As for the impact: 

1. The problem with the custom oracle is that it has fixed immutable price, which can't be changed later on. And it's known that oracle prices fluctuate, for example if we look at the Chainlink's [ETH/USD](https://data.chain.link/feeds/polygon/mainnet/eth-usd) for Polygon, the price for the last week went down from ~2,655$ to ~ 2,317$ (can be seen in the diagram). So essentially it will have negative impact on users or the protocol. The fix here would be if the price can be updated, by introducing a setter function.

2. Additionally the Chainlink oracle is working on Polygon, it has available feeds, the problem here is that the sequencer check must be skipped in order to successfully retrieve the prices, as it's written in the report.

**Comment by WangSecurity** [comment]
Result:
Invalid 
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [InfectedIsm](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/550/#issuecomment-2353651314): rejected
